### PR TITLE
Closes #2299 fully removing deprecated arguments from package

### LINKED ISSUE #2299: General Issue: Move functions argument to the next phase of deprecation
### Background Information

We have a few function arguments that need to be progressed in their stage of deprecations.

image

### Definition of Done

- [ ] The above screenshotted function arguments are moved along in the deprecation process
- [ ] Double check that these functions have been removed from admiral 
image

- [ ] Check that none of the deprecated arguments are being used in templates/vignettes.

### PR DESCRIPTION
**Pull request by ddsjoberg**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #2299 into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF version of it to the same folder.
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by ddsjoberg** [comment]
updates made
- `compuete_egfr(wt)` argument fully removed
- `derive_extreme_records(filter)` was previously removed; **no change**
- `derive_param_computed(analysis_value, analysis_var)` arguments fully removed
- `derive_var_shift(na_val)` argument fully removed
- `derive_expected_records(dataset_expected_obs)` argument fully removed
- `derive_var_ontrtfl(span_period)` deprecation messaging about `span_period = "Y"` values is removed.

I double checked the deprecated functions listed in the original issue, and they have indeed been removed.

I haven't updated the NEWS because I am a little confused about our messaging for deprecations. All these deprecations were messaged in the `v1.0.0` release NEWS entry.

**Comment by zdz2101** [comment]
@ddsjoberg I bundled the rest of the deprecation and NEWS blurb into this, @bms63 I think this should be just about done minus the weird renv-based stuff that seems to be breaking a few of the checks

**Comment by bms63** [comment]
> @ddsjoberg I bundled the rest of the deprecation and NEWS blurb into this, @bms63 I think this should be just about done minus the weird renv-based stuff that seems to be breaking a few of the checks

awesome hopefully the renv stuff gets fixed here: https://github.com/pharmaverse/admiral/pull/2307

**Comment by bms63** [comment]
This looks good to me!!  Thanks @zdz2101  and @ddsjoberg.  We will get our deprecation/supersaying strategy sorted soon!!

**Pull request merged**
