### PR TITLE
#911 updated format function in derive_var_disposition_status to have…

### LINKED ISSUE #911: Update derive_var_disposition_status.R to have more meaningful argument
Currently the argument uses x - but I think it should have a more meaningful name 

image

### PR DESCRIPTION
**Pull request by teckla-gsk**
Close #911 
… a meaningful par i.e. change 'x' to 'status'

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Review by bms63 — APPROVED** [review]
Looks good to me! @kabis-ops What do you think?

**Review by kabis-ops — COMMENTED** [review]
Hi, the update is fine with me too.
Should we update this in the ADSL vignette?
````
format_eosstt <- function(x) {
  case_when(
    x %in% c("COMPLETED") ~ "COMPLETED",
    x %in% c("SCREEN FAILURE") ~ NA_character_,
    !is.na(x) ~ "DISCONTINUED",
    TRUE ~ "ONGOING"
  )
}
```
or in a separate issue?

**Comment by bms63** [comment]
That is a good catch.  @teckla-gsk do you mind updating the adsl.Rmd vignette as well?  Are you able to render the packagedown site on Desktop?  If not I can pull, render and check the site after you update it.

**Comment by bms63** [comment]
Can you put Closes #911 at the top of the tome that is our PR template.  Supposedly it will auto-close the issue once we merge into main.

**Comment by teckla-gsk** [comment]
@bms63  @kabis-ops should we update the vignette? The function that was updated is the `format_eoxxstt_default()` while the vignette is pointing users to create a custom function if the default is not used?

**Comment by bms63** [comment]
> @bms63 @kabis-ops should we update the vignette? The function that was updated is the `format_eoxxstt_default()` while the vignette is pointing users to create a custom function if the default is not used?

Well then...I guess not!  :)  Can you update the top of the PR template with Closes #911.  @kabis-ops looks all good to me!

**Comment by teckla-gsk** [comment]
ok Vignette updated to replace the 'x' arguments to meaningful vars

**Review by kabis-ops — APPROVED** [review]
Thanks!

**Comment by bms63** [comment]
Hi Teckla,

Some of the merge conflicts still came through.

**Comment by teckla-gsk** [comment]
@bms63 on my side I see the checks as incomplete

**Comment by bms63** [comment]
@kabis-ops  Hey Samia.  Are you able to re-review?  I changed one piece of the adsl vigneete to use var_input rather the name of the variable.  Let me know if you agree.  everything else was Teckla's update

**Review by millerg23 — APPROVED** [review]
@bms63 your change seems fine to me, I had a quick chat with Samia as well.

**Pull request merged**
