### PR TITLE
Closes #1214 1214_fix_derive_param_first_event: fix it

### LINKED ISSUE #1214: Bug: derive_param_first_event() - AVALN
### What happened?

The function derive AVALN instead of AVAL

### Session Information

R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods   base     

other attached packages:
[1] lubridate_1.7.4    roxygen2_7.2.0     rlang_1.0.2        admiral.test_0.2.0 admiral_0.7.0     
[6] dplyr_0.8.5        admiralonco_0.0.0  testthat_3.0.0    

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.3        pillar_1.4.3      compiler_3.6.3    remotes_2.1.1     prettyunits_1.1.1
 [6] tools_3.6.3       digest_0.6.25     pkgbuild_1.0.6    pkgload_1.0.2     memoise_1.1.0    
[11] lifecycle_1.0.1   tibble_3.0.0      pkgconfig_2.0.3   cli_3.3.0         rstudioapi_0.11  
[16] xfun_0.30         xml2_1.3.3        knitr_1.39        withr_2.4.3       stringr_1.4.0    
[21] fs_1.5.2          desc_1.4.0        vctrs_0.3.8       devtools_2.2.2    hms_0.5.3        
[26] rprojroot_1.3-2   tidyselect_1.0.0  glue_1.6.0        R6_2.4.1          processx_3.5.2   
[31] sessioninfo_1.1.1 tidyr_1.0.2       purrr_0.3.3       callr_3.7.0       magrittr_2.0.3   
[36] usethis_2.1.5     backports_1.1.5   ps_1.6.0          ellipsis_0.3.2    assertthat_0.2.1 
[41] diffdf_1.0.4      renv_0.13.0       stringi_1.4.6     crayon_1.3.4    

### Reproducible Example

Example from the reference page
image

### PR DESCRIPTION
**Pull request by bundfussr**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by rossfarrugia** [comment]
Thanks Stefan! All looks reasonable to me but probably best @thomas-neitmann or @kabis-ops reviews and then once merged should be an easy check if it solved the ADRS issue for admiralonco

**Comment by bundfussr** [comment]
@thomas-neitmann , it seems that the `patch` branch is not protected. Could you change this and also define the same checks as required as for `devel`?

**Review by kabis-ops — COMMENTED** [review]
Sorry i was not up to date with admiral.test so it took longer.
Everything looks fine, except, I wonder now, if AVAL should always be calculated. In the example, AVAL is not in ADRS but is derived with `derive_param_first_event`.0 Maybe another issue? If yes let me know and I approve the PR

**Comment by bundfussr** [comment]
@kabis-ops , this is a good question. I would not change it now.

Could you create a discussion issue? I think hard coding `ADT` and `AVALC` is questionable as well.

**Pull request merged**
