### PR TITLE
Remove workarounds for R v3.5 compatibility

### PR DESCRIPTION
**Pull request by thomas-neitmann**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md`
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue so that it closes after successful merging. 
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Comment by millerg23** [comment]
@thomas-neitmann , @bundfussr 
I saw Thomas message on Slack, about replacing any calls to function `gather()` with function `pivot_longer()`.  {admiral} function `derive_vars_query` calls `gather()` twice.
On line 87 I replaced `gather() %>%` with `pivot_longer(c(NAM, CD, SC, SCN), names_to = "key", values_to = "value") %>%` and ran the unit tests successfully.
On line 142 I replaced `gather(key = "TERM_LEVEL", value = "TERM_NAME_ID", -static_cols) %>%` with `pivot_longer(-static_cols, names_to = "TERM_LEVEL", values_to = "TERM_NAME_ID") %>%`, I then ran the unit test and the tests fail.
I ran the test separately,
```
query <- tibble::tribble(
  ~VAR_PREFIX, ~QUERY_NAME, ~TERM_LEVEL, ~TERM_NAME, ~QUERY_ID, ~TERM_ID,
  "CQ40", "My Query 1", "AEDECOD", "PTSI", 1, NA,
  "CQ42", "My Query 2", "AELLTCD", NA_character_, 2, 1
)

my_ae <- tibble::tribble(
  ~USUBJID, ~ASTDY, ~AEDECOD, ~AELLT, ~AELLTCD,
  "1", 1, "PTSI", "other", NA,
  "1", 2, "PTSI", "LLTSI", NA,
  "1", 3, NA, NA, 1
)

actual_output2 <- derive_vars_query(my_ae, dataset_queries = query)
```
And I get the following ERROR:
```
Error: No common type for `AEDECOD` <character> and `AELLTCD` <double>.
Run `rlang::last_error()` to see where the error occurred. 
```
I ran `rlang::last_error()` and `rlang::last_trace()` and got the following:
```
> rlang::last_trace()
<error/vctrs_error_incompatible_type>
No common type for `AEDECOD` <character> and `AELLTCD` <double>.
Backtrace:
     █
  1. ├─global::derive_vars_query(my_ae, dataset_queries = query)
  2. │ └─`%>%`(...)
  3. │   ├─base::withVisible(eval(quote(`_fseq`(`_lhs`)), env, env))
  4. │   └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  5. │     └─base::eval(quote(`_fseq`(`_lhs`)), env, env)
  6. │       └─`_fseq`(`_lhs`)
  7. │         └─magrittr::freduce(value, `_function_list`)
  8. │           └─function_list[[i]](value)
  9. │             └─tidyr::pivot_longer(...)
 10. │               └─tidyr::pivot_longer_spec(...)
 11. │                 └─vctrs::vec_ptype_common(...)
 12. ├─vctrs:::vec_ptype2_dispatch_s3(x = x, y = y, x_arg = x_arg, y_arg = y_arg)
 13. ├─vctrs::vec_ptype2.character(x = x, y = y, x_arg = x_arg, y_arg = y_arg)
 14. └─vctrs:::vec_ptype2.character.default(...)
 15.   └─vctrs::vec_default_ptype2(x, y, x_arg = x_arg, y_arg = y_arg)
 16.     └─vctrs::stop_incompatible_type(x, y, x_arg = x_arg, y_arg = y_arg)
 17.       └─vctrs:::stop_incompatible(...)
 18.         └─vctrs:::stop_vctrs(...)
```

Any suggestions?

**Comment by bms63** [comment]
Does it matter if you use `NA_character_`  versus `NA`?

**Comment by millerg23** [comment]
I made some updates to replace function `gather()` with `pivot_longer()`. In particulr changes made to 'derive_vars_query(()`  function. @bundfussr and @thomas-neitmann could you take a look? Let me know if there is a more elegant way of fixing the numerics to character vars.

**Comment by thomas-neitmann** [comment]
Looks good to me 👍 

I cannot approve this PR as I opened it myself. Please go ahead @bundfussr.

**Review by bundfussr — APPROVED** [review]

**Pull request merged**
