### PR TITLE
Closes #2205 add previous website links

### LINKED ISSUE #2204: DESCRIPTION file has incorrect version
We've released v0.12.3, but the DESCRIPTION file has v.012.2.9001 

https://github.com/pharmaverse/admiral/blob/9cb431679f84acba6f386c2cb1ebb36c7eec21b2/DESCRIPTION#L4

### LINKED ISSUE #2205: Add Versions menu to the pkgdown site
@cicdguy has turned off the multiversion docs, and now we can add our dropdown directly to `_pkgdown.yml`. The dropdown will have Dev, Current Release, and Previous Releases, where the latter links to the new article.

### PR DESCRIPTION
**Pull request by ddsjoberg**
@cicdguy and I have been working on the pkgdown site updates. I am now adding back a link to the previous versions of the website. We could keep the menu to what it looked like before, or (and my preference) is to add a small history button on the RHS of the nav bar that links to the historic versions of the website. Thoughts?

image

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #2204, Closes #2205 into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by jeffreyad** [comment]
Would it be possible to add a link to the dev version of the website?

**Comment by ddsjoberg** [comment]
> Would it be possible to add a link to the dev version of the website?

Yes, we could add it the versions article very easily

**Comment by ddsjoberg** [comment]
@jeffreyad added dev version link to the versions article
image

**Comment by jeffreyad** [comment]
> @jeffreyad added dev version link to the versions article image

Thanks @ddsjoberg that looks great!

**Review by zdz2101 — APPROVED** [review]
Fire away! Won't know how it looks until a full go right?

**Pull request merged**
