### PR TITLE
Rstudio addin added

### LINKED ISSUE #714: Automate adding function name and test number to the test title
A function should be implemented which adds the function name and a test number to the title of the tests. Additionally it should add a comment before the test such that it is displayed in the TOC in RStudio.
For example
```
test_that("duration and unit variable are added", {
...
}
```
should be transformed to
```
#---- derive_vars_aage, test 1: duration and unit variable are added ----
test_that("derive_vars_aage, test 1: duration and unit variable are added", {
...
}
```
If the function name and test number are already in the title, it should be updated if necessary.

### PR DESCRIPTION
**Pull request by slamao**
* Closes pharmaverse/admiraldev#1 
* Implemented as an addin but does not have to be this way, let me know!
* To use the addin, one needs to reinstall the package (and run `devtools::load_all()`), then the addin should emerge 
image
* This can also be run programmatically, check out the following pseudo-code:
    1. use `list.files` to get the list of files that are to be updated
    2. in a for loop, go through each file: open it using `rstudioapi::navigateToFile` and run `format_test_that_file`

_______

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by slamao** [comment]
Hi @bms63 , good point with the code coverage. 
This issue seemed to be a nice use-case for the addin but it does not need to be so at all! It can be converted it into a simple function where the developer would supply the name of the file as a parameter. Or let me know if you have other ideas (I am honestly not sure how else to handle this). 
Anyway, as long as it stays in this package, I think it will always negatively impact the code coverage, unless we add unit tests (which really may be quite complex if used as addin, as you pointed out). 
Also happy to move it to admiral.dev if there will be a general feeling for it.
We are still reviewing this update in the team so some new changes may appear ...

**Comment by bms63** [comment]
If you all can write tests for the function, then that is huge win for anything downstream, e.g. admiraldev .  Thanks again for doing this - I'm super excited for this to be used on our tests.

**Comment by slamao** [comment]
I think we will be able to actually write unit tests for this, will update this PR later on ...

**Review by bundfussr — CHANGES_REQUESTED** [review]
It seems that renumbering does not work. I called the addin for `test-compute_duration`, removed the first unit test, and called the addin again. I got
```
# ---- compute_duration, test 2: fractional duration ----
# ---- compute_duration, test 1: compute_duration, test 2: fractional duration ----
test_that("compute_duration, test 1: compute_duration, test 2: fractional duration", {
  expect_equal(
    compute_duration(
      ymd_hms("2020-12-06T15:00:00"),
      ymd_hms("2020-12-24T09:00:00"),
      floor_in = FALSE,
      add_one = FALSE
    ),
    17.75
  )
})
```
There are also issues when the file is modified but not saved. When I did the same as above without saving after removing the first unit test, I got:
```
test_that("compute_duration, test 1: default duration, i.e., relative day", {
test_that("compute_duration, test 2: fractional duration", {
  expect_equal(
    compute_duration(
      ymd_hms("2020-12-06T15:00:00"),
      ymd_hms("2020-12-24T09:00:00"),
      floor_in = FALSE,
      add_one = FALSE
    ),
    17.75
  )
test_that("compute_duration, test 2: fractional duration", {

```

**Comment by bundfussr** [comment]
Thanks, @slamao , the renumbering is working well now.

The addin also works if there are unsaved changes but the result is unexpected because the changes are discarded. I would prefer that the changes are saved before updating the titles or ideally ask the user if the changes should be saved or discarded.

**Comment by slamao** [comment]
> Thanks, @slamao , the renumbering is working well now.
> 
> The addin also works if there are unsaved changes but the result is unexpected because the changes are discarded. I would prefer that the changes are saved before updating the titles or ideally ask the user if the changes should be saved or discarded.

Unfortunately there is no way to find out if the file is saved or not (there is not such a function in rstudioapi package, it is a requested feature currently https://github.com/rstudio/rstudioapi/issues/230). So we can either always save it or keep it as it is now. What do you prefer? Shall we always save before updating the file?

**Comment by bundfussr** [comment]
I would prefer saving before updating because it is the more common case.

**Comment by slamao** [comment]
Sounds good, code updated

**Comment by bundfussr** [comment]
Thanks

**Comment by slamao** [comment]
Moved to https://github.com/pharmaverse/admiraldev/pull/6

**Pull request closed without merging**
