### PR TITLE
Closes #1697 add keep source vars param@devel

### LINKED ISSUE #1697: Feature Request: Add `keep_source_vars` parameter
### Feature Idea

Functions which add observations to a dataset and the new observations are selected (and not summarized) from a dataset should provide the `keep_source_vars` argument. This argument allows to specify which variables from the selected observations should be kept, e.g., `ADT`, `AVISIT`, `RSDTC`, ... It should accept tidyselect expressions. Then `keep_source_vars= everything()` could be specified to keep all variables.

The default of the parameter should be `everything()`.

An example should be provided how to select everything except some specific variables.

*Affected functions*: `derive_extreme_records()`, `derive_param_exist_flag()`

### Relevant Input

_No response_

### Relevant Output

_No response_

### Reproducible Example/Pseudo Code

```
derive_param_extreme_event(
  adrs,
  dataset_adsl = adsl,
  dataset_source = adrs,
  filter_source = PARAMCD == "OVR" & AVALC == "PD",
  order = vars(ADT),
  new_var = AVALC,
  keep_source_vars = vars(RSDTC, VISIT, VISITNUM),
  true_value = "Y",
  false_value = "N",
  mode = "first",
  set_values_to = vars(
    PARAMCD = "PD",
    PARAM = "Disease Progression",
    ANL01FL = "Y",
    ADT = ADT
  )
)
```

### PR DESCRIPTION
**Pull request by gg106046**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by bms63** [comment]
Hi Gayatri - This branch seems way out of date from the `devel`.  Did you recently create it?  The news is almost empty in your branch, but we have a lot of entries in it.

**Comment by gg106046** [comment]
> Hi Gayatri - This branch seems way out of date from the `devel`. Did you recently create it? The news is almost empty in your branch, but we have a lot of entries in it.

Hi Ben! Yeah I had created the branch last month sometime. That's what I was wondering since there are many merge conflicts. When I did a pull, it said it was up to date. Not sure why it did not pull the latest devel branch.
What should be the solution here? Cause both the files 'derive_param_extreme_event.R' and 'derive_extreme_records.R' have been updated recently, and I'm not sure it would be a easy fix of merge conflict. Should I just delete the branch, create a new one and do the updates again?

**Comment by zdz2101** [comment]
I agree with @bms63 starting off a fresh branch is always the easiest solution, but if you want to try fixing it "the old-fashioned way" its an invaluable lesson too

image

**Comment by gg106046** [comment]
> > > Hi Gayatri - This branch seems way out of date from the `devel`. Did you recently create it? The news is almost empty in your branch, but we have a lot of entries in it.
> > 
> > 
> > Hi Ben! Yeah I had created the branch last month sometime. That's what I was wondering since there are many merge conflicts. When I did a pull, it said it was up to date. Not sure why it did not pull the latest devel branch. What should be the solution here? Cause both the files 'derive_param_extreme_event.R' and 'derive_extreme_records.R' have been updated recently, and I'm not sure it would be a easy fix of merge conflict. Should I just delete the branch, create a new one and do the updates again?
> 
> i have found using the RStudio Git Tab that I have to do pull down multiple times when switching branches. I think using the terminal is the best option.
> 
> Deletling this branch and making a new one off `devel` is probably the quickest and easiest solution. There are other ways to do it, but they can take a while to implement for first-timers :)

Sure Ben. Then I'll just create a new one and delete this branch.

**Comment by gg106046** [comment]
> I agree with @bms63 starting off a fresh branch is always the easiest solution, but if you want to try fixing it "the old-fashioned way" its an invaluable lesson too
> 
> image

Thanks Zelos! For now I'm creating a new branch since it's the quickest solution.

**Pull request closed without merging**
