### PR TITLE
Closes #2372 tracking and addressing changes from admiraldev

### LINKED ISSUE #2372: General Issue: Tracking updates for admiraldev
### Background Information

admiraldev is updating assertion functions around better messaging.  This issue is to help understand and fix any problems that arise from the upstream updates.

* https://github.com/pharmaverse/admiraldev/issues/367

### Definition of Done

- [x] Place Remotes into DESCRIPTION
- [x] Document impacted functions in Developer Notes (if feasible)
- [x] Update impacted functions
- [ ] Investigate examples, vignettes, templates where impacted
- [ ] Profit

### Issues completed around this update to admiraldev
* https://github.com/pharmaverse/admiral/issues/2375
* https://github.com/pharmaverse/admiral/issues/2382
* Minor update done here: https://github.com/pharmaverse/admiral/pull/2393
* Minor update done here: https://github.com/pharmaverse/admiral/pull/2397
* https://github.com/pharmaverse/admiral/issues/2406
* https://github.com/pharmaverse/admiral/issues/2404
* https://github.com/pharmaverse/admiral/issues/2403
* https://github.com/pharmaverse/admiraldev/pull/450

### PR DESCRIPTION
**Pull request by bms63**
Tracking changes happening in admiraldev

### CODE REVIEW

**Comment by zdz2101** [comment]
@pharmaverse/admiral I noticed the CI/CD error that appears here in the dummy PR's, is this a known bug?

**Comment by bms63** [comment]
> @pharmaverse/admiral I noticed the CI/CD error that appears here in the dummy PR's, is this a known bug?

What error appear?

**Comment by zdz2101** [comment]
Looks like something related to `derive_param_exposure()` 
image

**Comment by zdz2101** [comment]
perhaps related to the changes being made on `admiraldev` ?

**Comment by bms63** [comment]
> Looks like something related to `derive_param_exposure()` image

ummm....I guess I was wrong about admiraldev not being picked up anymore in our CI actions without turning on Remotes.  Something must be happening with staged.dependencies still??

**Comment by bms63** [comment]
@millerg23 @ddsjoberg so I guess staged.dependencies is still engaged as this step happens before it gets to Remotes.  Seems to be impacting other PRs 
image

**Comment by millerg23** [comment]
@bms63 do you want me to update the unit tests, based on whats been updated so far in `admiraldev` (main branch). Or wait until all the ERROR messaging updates are complete in `admiraldev`??

**Comment by bms63** [comment]
> @bms63 do you want me to update the unit tests, based on whats been updated so far in `admiraldev` (main branch). Or wait until all the ERROR messaging updates are complete in `admiraldev`??

Maybe we should wait until everything is completed in admiraldev - might be nice to start collecting in #2372 all the updates needed.

maybe folks working on other PRs can just check locally that admiral is still working with CRAN version of admiraldev

**Comment by bms63** [comment]
@manciniedoardo any idea what is up with this dummy_study_design.png?

**Pull request closed without merging**
