### PR TITLE
Closes #2526 data raw data round/2

### LINKED ISSUE #2526: General Issues: data-raw/data Round 2
> I'm ready to merge this into `main`. @pharmaverse/admiral any last thoughts or concerns?

Sorry for the late reply. I was off because the 3rd October is a bank holiday here.

I think the PR shouldn't have been merged. There are a lot of unresolved issues:
- The `create_*()` scripts don't run.
- The scripts include code which is never run.
- `data-raw/admiral_adlb.R` was added to the repo but it is never used.
- The `data-backup` folder should be removed because it is not necessary but increases the size of the repo (and the scripts do not update the backup anyway).
- ...

@bms63 , how should we move on?

_Originally posted by @bundfussr in https://github.com/pharmaverse/admiral/issues/2494#issuecomment-2397305625_

### PR DESCRIPTION
**Pull request by jimrothstein**
…ws errors.

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [ ] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF and a PNG version of it to the same folder. (The PNG version can be created by taking a screenshot of the PDF version.)
- [ ] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers). A Developer Notes section is available in `NEWS.md` for tracking developer-facing issues.  
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by bms63** [comment]
Can you paste the error from diffdf please?

**Comment by jimrothstein** [comment]
**admiral_adlb**  (no problems with **admiral_adsl**)

Differences found between the objects!

Summary of BASE and COMPARE
  ==================================================================
    PROPERTY             BASE                       COMP            
  ------------------------------------------------------------------
      Name             adlb_old                 admiral_adlb        
     Class     "tbl_df, tbl, data.frame"  "tbl_df, tbl, data.frame" 
    Rows(#)              3779                       3779            
   Columns(#)             111                        115            
  ------------------------------------------------------------------


There are columns in BASE and COMPARE with different modes !!
  ================================
   VARIABLE  MODE.BASE  MODE.COMP 
  --------------------------------
    AGEGR1    numeric   character 
  --------------------------------


There are columns in BASE and COMPARE with different classes !!
  ==================================
   VARIABLE  CLASS.BASE  CLASS.COMP 
  ----------------------------------
    AGEGR1     factor    character  
  ----------------------------------


There are columns in COMPARE that are not in BASE !!
  =========
   COLUMNS 
  ---------
   DTHDTF  
   DTHCAUS 
   DTHDOM  
   DTHCGR1 
  ---------

**Comment by bms63** [comment]
Hey @jimrothstein 

I don't see this issue you idenfitied in the diffdf output after re-running your `create_` script.  These are expected.  

image

For those ADSL variables - no biggie if I am missing something as they won't impact the adlb vignette.

**Comment by bms63** [comment]
I also removed the old admiral_adlb script - I actually like the use of the verb `create_` here.  Think this should be adopted in these other three files.

**Comment by bms63** [comment]
image

**Comment by bms63** [comment]
@jimrothstein I already update with `create_`  

There is something amiss with derive_vars_query(admh, quries_mh) code when I run it.  I am not familiar with it.  Going to make another issues as like to merge this change in 
image

**Pull request merged**
