### PR TITLE
#841 creating adae variables for astdtm and trtemfl

### PR DESCRIPTION
**Pull request by donyunardi**
As instructed, I created the PR to assess if the functions are useful and within the scope of the package.

I need to mention that the creator of these functions (Sandra Ott) was using functions from the newer dplyr version  (dplyr >= 1.0) so I need to update the renv lock file for your review.

I can finish the rest of the checklists on the bottom if we think this function is useful.

----------------

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://roche-gsk.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://roche-gsk.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://roche-gsk.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::documents()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md`
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://roche-gsk.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Comment by thomas-neitmann** [comment]
Thanks a lot @donyunardi!

This does appear to be rather Roeche specific so might be best suited for our internal {admiral.roche} package. What do you think @bundfussr @kabis-ops @rossfarrugia @koegerr?

**Comment by rossfarrugia** [comment]
my understanding below: (feel free to correct me anyone!)

- adae.astdtm - Roche has a convention not to allow partial AE dates to be imputed to pre-first treatment date, as we assume more conservative that the event occurred after treatment. in the ADaM IG i can't see any specific CDISC guidance around how to do imputations and it does make me feel this is one of those "Roche-specific" cases. @bms63 - does GSK do similar? i'll ask the same question on our admiral user Slack channel to see any other company approaches.

- adae.trtemfl (treatment-emergent flag) - i couldn't find anything in ADaM IG for this so guessing Roche-specific again, but will check on the Slack channel.

**Comment by bundfussr** [comment]
I agree that these function are Roche-specific.

However, I wonder if we should update admiral to support such derivations. The code of the two derivations is quite long.

Avoiding that the imputed AE start date is before treatment start date is already implemented in admiral. But at the moment treatment start date is not taken into account if the year is missing. For improving imputation we already have an issue (https://github.com/pharmaverse/admiral/issues/727).

By the way, should we have an admiral.roche package at github.com for derivations like these two and another admiral.roche package at github.roche.com for really Roche-internal functions like accessing Roche databases? Even if other companies do not use exactly the same derivation for ASTDTM and TRTEMFL, the code may be of interest for them and they may be able to use part of it or identify which part could be moved to admiral.

**Comment by rossfarrugia** [comment]
thanks @bundfussr - i missed the min_dates argument for derive_vars_dtm. Do we even need a new Roche function here for ASTDTM then - could we just reuse this if it's being updated anyway?

on the company-specific pieces we've gone back and forth on whether to open source these in case people could benefit from them, but in truth imagine if 20 companies were using then who'd go through each and every repo looking for the code they need. i think better to just have the company-specific in your own private company repo and then if you ever see a new issue or Slack discussion requesting the same in admiral core then you could volunteer the company code. as long as some due dilligence is done first to ensure the code is actually company specific and people don't just choose to go company specific first, as the aim here of admiral is we all help each other to build for any shared needs.

**Comment by bundfussr** [comment]
Whether we could use the admiral function for the Roche ASTDTM derivation depends on what will be implemented in https://github.com/pharmaverse/admiral/issues/727. At the moment it is just a collection of all the feedback we received from the testers. We need to discuss what we want to implement.

I think most of the Roche derivation could be covered. There is only on point which is a bit strange and which maybe should not implemented in admiral: If the imputed AE start date is set to treatment start date, the complete datetime is used if year is missing while for all other cases the time part of TRTSDTM is replaced by 23:59:59. Looks inconsistent to me.

**Comment by rossfarrugia** [comment]
i added a comment for this back to the original issue as probably best to discuss there and then come back to the PR once we have an aligned plan of action. also in case i didn't say it before thanks @donyunardi and Sandra for starting this!! awesome to have you contributing to admiral.

**Comment by bms63** [comment]
Hello.  Is this still being actively worked on or should we close it out?

**Pull request closed without merging**
