### PR TITLE
use ascii quotes

### PR DESCRIPTION
**Pull request by romainfrancois**
I believe this is what cran `NOTE`s about in #2187

### CODE REVIEW

**Comment by bms63** [comment]
The NOTE lists twelve culprits.

**Comment by romainfrancois** [comment]
I'll investigate some more. This was a quick and dirty : 

```r
for (f in dir("r", full.names = TRUE)) { 
  txt <- readLines(f)
  non_ascii <- tools::showNonASCIIfile(f)
  if (length(non_ascii)) print(f) 
}
```

Some of them might also be in the associated `.Rd` file

**Comment by bms63** [comment]
I was just posting about this in our slack and if we should fix - lol.  You are like an ascii angel :) 

We might have some in our News.md as well.

**Comment by bms63** [comment]
@bundfussr I thought the quotes might be an issue!  :)

**Comment by bms63** [comment]
Thank you @romainfrancois!

**Pull request merged**
