### PR TITLE
Closes #2152 update install instructions

### LINKED ISSUE #2151: Shorten dev version install instructions
When we switch to using `Remotes:` in place of staged dependencies, let's also simplify the installation instructions for the dev version of admiral. At the moment, the far-less used instructions are given a bit too much real estate on the home page. 

What is looks like now:
image

Proposal:
1. Use a code block for `install.packages("admiral")` instead of `code formatting`.
2. Update the code block for dev version to something like this

```r
# install.packages("devtools")
devtools::install_github("pharmaverse/admiral")
```

### LINKED ISSUE #2152: Add vbump workflow
When the dust settles from the latest patch release and the many open PRs are merged, we discussed adding the vbump workflow to admiral.

### PR DESCRIPTION
**Pull request by ddsjoberg**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #2151 into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Review by bms63 — COMMENTED** [review]
do we need to update the DESCRIPTION file with remotes so they get the latest and greatest from the helper packages?

**Comment by ddsjoberg** [comment]
> do we need to update the DESCRIPTION file with remotes so they get the latest and greatest from the helper packages?

@bms63 if we make an update that depends on a dev version of the helper packages, then we should add `Remotes:` to the `DESCRIPTION`. Otherwise, we should just keep it as is.

**Comment by bundfussr** [comment]
> > do we need to update the DESCRIPTION file with remotes so they get the latest and greatest from the helper packages?
> 
> @bms63 if we make an update that depends on a dev version of the helper packages, then we should add `Remotes:` to the `DESCRIPTION`. Otherwise, we should just keep it as is.

Could we document this somewhere?
Would it harm to add `Remotes:` even if currently the devel version does not depend on devel versions of dependencies? Adding and removing `Remotes:` looks cumbersome to me and most likely we will forget it.

**Comment by ddsjoberg** [comment]
We'll never forget to add `Remotes:` when it's needed because our tests should fail when there is a breaking change in an upstream package.

We'll never forget to remove it, because CRAN will reject us if we submit with a `Remotes:` in the DESCRIPTION

**Comment by bms63** [comment]
I'll make a note to update in the prog docs - as none of us were aware of this Remotes stuff until you came along Daniel.

**Pull request merged**
