### PR TITLE
Closes #1471 warnings related to derive_var_agegr_fda

### LINKED ISSUE #1471: General Issue: Remove tests for `derive_var_agegr_fda` and `derive_var_agegrp_ema`
### Background Information

These tests for the above functions were not removed and are causing small issues in the tests checking.  

image

Functions being deprecated should have their tests removed.  

image

### Definition of Done

Tests `derive_var_agegr_fda` and `derive_var_agegrp_ema` in the `test-derive_vars_aage.R` file are removed and everything works well and good.

### PR DESCRIPTION
**Pull request by AniaGolab**
Commit concerning derive_var_agegr_fda and derive_var_agegr_ema (NOT derive_var_agegr_ema as per title).
removed derive_var_agegr_ema and derive_var_agegr_fda from the test-derive_vars_aage.

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by AniaGolab** [comment]
Hi @thomas-neitmann my edits are concerning derive_var_agegr_fda and derive_var_agegr_ema (NOT derive_var_agegr_ema as per title of the issue). The derive_var_agegr_ema was not in the file and there was no warnings concerning it. 

I removed derive_var_agegr_ema and derive_var_agegr_fda from the test-derive_vars_aage which were causing warnings. 

One thing to note is that the code is failing 3 tests concerning the derive_derived_param:
Failure (test-deprecation.R:102:3): derive_derived_param Test 1: A warning is issued if `derive_derived_param()` is called
`derive_derived_param(...)` did not produce any warnings.
Failure (test-deprecation.R:120:3): derive_vars_merged_dt: a deprecation warning is issued
`derive_vars_merged_dt(...)` did not produce any warnings.
Failure (test-deprecation.R:136:3): derive_vars_merged_dtm: a deprecation warning is issued
`derive_vars_merged_dtm(...)` did not produce any warnings.
this is failing even without my edits - should I look into this issue as well?

**Comment by bms63** [comment]
If you restart your R sesssion then that failure will go away.  Lifecycle only produces that warning every 8 hours and so if you run it once then it passes, but a second time it doesn't produce any warnings and it fails.

**Comment by AniaGolab** [comment]
Thank you Ben! Ok so now we have: [ FAIL 0 | WARN 0 | SKIP 0 | PASS 467 ].

**Review by thomas-neitmann — APPROVED** [review]

**Comment by thomas-neitmann** [comment]
Congrats on getting your first PR merged @AniaGolab 🥳

**Pull request merged**
