### PR TITLE
demo of using tags to patch/hotfix for a release

### PR DESCRIPTION
**Pull request by bms63**
@bundfussr this is demoing creating a patch branch off a tag.  This way we don't need to maintain a patch branch going forward. 

I just followed this - https://stackoverflow.com/questions/10940981/how-to-create-a-new-branch-from-a-tag

I think we did this recently with some of the `0.12.x` patching.  @zdz2101 do you recall if we branched off a tag?

It seems to work!

### CODE REVIEW

**Comment by bms63** [comment]
So I had to make two branches off the `v1.0.0` tag so we could track the changes and it ins't getting merged to `main`

ONce this is completed we can release from this demo branch and merge the change into `main`

**Comment by bms63** [comment]
code for creating the branches 
image

**Comment by bundfussr** [comment]
As far as I remember the issue was not creating a branch from a tag. I think @cicdguy mentioned that using the patched version issues warnings if the branch was deleted.

By the way, why do you want to get rid of the `patch` branch?

**Comment by bms63** [comment]
> As far as I remember the issue was not creating a branch from a tag. I think @cicdguy mentioned that using the patched version issues warnings if the branch was deleted.
> 
> By the way, why do you want to get rid of the `patch` branch?

I'm just focused on trying to simplify things, but if the solution to "our current solution" is complicated then we can definitely keep the patch branch.

**Pull request closed without merging**
