### PR TITLE
Closes #849 Create template for ADPC@devel

### LINKED ISSUE #849: Create ADPC

### PR DESCRIPTION
**Pull request by RealSlimMahdi**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by RealSlimMahdi** [comment]
Making the PR ready for review as @thomas-neitmann mentioned to me that the checks failing were no big deal

**Comment by bms63** [comment]
@RealSlimMahdi We are doing a release on December 5th.  Do you think this can be completed before that time?

**Comment by RealSlimMahdi** [comment]
I committed the code that I consider final from my pov. I know that @thomas-neitmann is working with the Clin Pharm Team to create process documents and I am not involved. @VincentBuchheit do you have anything to add?

**Comment by bms63** [comment]
Could you fix the CI/CD failing checks please

**Comment by thomas-neitmann** [comment]
@jeffreyad Is the code here of any help for creatind the ADNCA template?

**Comment by jeffreyad** [comment]
> @jeffreyad Is the code here of any help for creatind the ADNCA template?

Yes, I'm updating the existing code to include the timing variables, e.g. NFRLT, AFRLT, NRRLT, ARRLT.  I will be using the new `derive_vars_joined` function and expanding dosing records with `create_single_dose_dataset`

**Comment by RealSlimMahdi** [comment]
@VincentBuchheit is also working on this PR, I'll wait that he pushes his commit before correcting the CICD, at the time, the checks crashed because of an issue in the devel branch, that's why I didn't bother.

**Comment by jeffreyad** [comment]
I updated template to use nominal_time parameter for `create_single_dose_dataset()`  #1640 #1643.

I added additional baselines from VS and rearranged some steps to be consistent with new vignette for PK ADNCA/ADPC programming #1639 #1651

**Comment by bms63** [comment]
@jeffreyad just checking in on status of this PR/Issue?

**Comment by jeffreyad** [comment]
> @jeffreyad just checking in on status of this PR/Issue?

@bms63 I think this is ready, however it also depends on #1643.  It could also be updated to replace vars() with exprs() #1688. I can make that change now if needed.

**Comment by bms63** [comment]
Hey @jeffreyad you are going to need to attach `@devel` to the end of the branch to get the checks to pass, which I think will mean this PR will have to be closed.  Can you link this PR in the new PR as it has some discussion in it that I would like to keep for posterity.

Hopefully, we will have vars() and exprs() PR done by the EOW.  Please make sure it works with vars() first and hopefully EOW will be smooth transition.

thanks again for shepharding this through!!

**Comment by jeffreyad** [comment]
> Hey @jeffreyad you are going to need to attach `@devel` to the end of the branch to get the checks to pass, which I think will mean this PR will have to be closed. Can you link this PR in the new PR as it has some discussion in it that I would like to keep for posterity.
> 
> Hopefully, we will have vars() and exprs() PR done by the EOW. Please make sure it works with vars() first and hopefully EOW will be smooth transition.
> 
> thanks again for shepharding this through!!

Hi @bms63 I created new PR #1700

**Comment by bms63** [comment]
Closing as @jeffreyad created another PR.

**Pull request closed without merging**
