### PR TITLE
Closes #1460: Added tests to increase test coverage for derive_vars_merged_lookup and get_not_mapped.

### LINKED ISSUE #1460: General Issue: Increase Test Coverage for `derived_merged.R`
### Background Information

We need to increase test coverage for our functions. The below screenshot has the function and gap in test coverage that we need to write additional unit tests for `derived_merged.R`.  Additional gaps in coverage not shown

image

### Definition of Done

New tests written that covers the red gap area for `derived_merged.R`.

Use `devtools::test_coverage()` to reproduce the report

### PR DESCRIPTION
**Pull request by DeclanHodges**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

Note that this file has 98% test coverage, but now has 100% coverage for all functions that are not on the depreciation path.

### CODE REVIEW

**Comment by DeclanHodges** [comment]
Hi all,
I'm coming across a warning when running the devtools::check() function (see below). Has anyone come across this before? I'm a bit confused as I haven't changed any code scripts to do with outputting PDFs. 
image

**Comment by thomas-neitmann** [comment]
> I'm coming across a warning when running the devtools::check() function (see below). Has anyone come across this before? I'm a bit confused as I haven't changed any code scripts to do with outputting PDFs.

That's a standard warning you get when you haven't installed this 'qpdf' tools on your machine. I assume your on Windows? Anyhow, you can just ignore it.

**Review by bms63 — COMMENTED** [review]
@DeclanHodges does this cover the gaps?  Did you run `devtools::test_coverage()` ?

**Comment by DeclanHodges** [comment]
> devtools::test_coverage()
Great, thanks Thomas. And yes, I'm on Windows. In that case, it passes all of the CMD checks then!

**Comment by bms63** [comment]
Hey Declan.  We will need to wait a second on this to fix the `admiral CI/CD Workflows / Check / ubuntu-20.04 (release) (pull_request)` Failure.  This is because of the `lifecycle` package being updated recently.  We have a fix and it is making it's way into `devel` soon.

Please go ahead and fix the lintr failure.

**Comment by DeclanHodges** [comment]
> Hey Declan. We will need to wait a second on this to fix the `admiral CI/CD Workflows / Check / ubuntu-20.04 (release) (pull_request)` Failure. This is because of the `lifecycle` package being updated recently. We have a fix and it is making it's way into `devel` soon.
> 
> Please go ahead and fix the lintr failure.

Hey Ben, thanks for letting me know. The lint issue is now fixed.

**Review by bms63 — CHANGES_REQUESTED** [review]
image
 
looks like these got messed up a bit.  Can you go through and fix please

**Comment by bms63** [comment]
Hey @DeclanHodges just seeing where we are at with this PR?

**Comment by bms63** [comment]
@DeclanHodges  Can you update your feature_branch.  Don't forgot to pull down if you need to work locally 

image

**Comment by DeclanHodges** [comment]
Hey @bms63, 
Sorry this PR slipped my mind! I've fixed the formatting issues of those comments. 

> @DeclanHodges Can you update your feature_branch. Don't forgot to pull down if you need to work locally
I must've forgotten to do that, thanks for the reminder!

**Pull request merged**
