### PR TITLE
New Github Action Workflows 🎉

### PR DESCRIPTION
**Pull request by dinakar29**
This closes https://github.com/insightsengineering/thevalidatoR/issues/54 where a proper naming convention is added to the validation report. The new version of thevalidatoR also addresses an issue where `tlmgr` throws an error if it isn't updated to the latest version.

Also, this PR adds 3 new Github Action workflows:

- Code style checks
- Auto-generation of man pages and checking if man pages are up-to-date
- Spellchecks

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Comment by thomas-neitmann** [comment]
Thanks a lot @dinakar29! I'll take a close look later this week and get back to you in cases any updates are needed.

**Review by thomas-neitmann — APPROVED** [review]
Looks great, thank you so much @dinakar29 👏 🥳

**Comment by dinakar29** [comment]
> Looks great, thank you so much @dinakar29 👏 🥳

One more thing - should we disable the R CMD Check job on R 3.5?

**Pull request merged**
