### PR TITLE
#1016 - extra dthcaus example

### LINKED ISSUE #1016: Documentation:  add DTHCAUS extra example
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

https://pharmaverse.github.io/admiral/reference/derive_var_dthcaus.html - could benefit from a non-standard and bit more complex example with 3 different sources and using DS twice with different filters. I had to figure this out when comparing it against such an option that exists in the Roche standard specs, so happy to add this example.

Also at https://pharmaverse.github.io/admiral/articles/adsl.html#derive-death-variables – “`dthcause_source()`  specifications” should be `dthcaus_source()`

### PR DESCRIPTION
**Pull request by rossfarrugia**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

Closes #1016

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@bundfussr hope you're ok to review this minor update. it was something i spotted when working on comparing against the Roche specs and from the examples given it wasn't obvious how to achieve this when using 2 different sets of records from the same dataset. i think the extra example should help users.

**Review by bundfussr — APPROVED** [review]

**Comment by bundfussr** [comment]
Hi @thomas-neitmann , could you have a look at the checks? It seems that "ubuntu-20.04 (3.6)" is blocking the merge but it does not run.

**Comment by bms63** [comment]
I can use my super powers to merge in as well.

**Comment by bundfussr** [comment]
I am not sure. Is this issue occurring only for this PR or is it a general issue?

**Comment by bms63** [comment]
it happened on my recent PR.  I checked with Thomas for mine and he said fine to merge in.  Lets wait for him to make the call @thomas-neitmann

**Comment by thomas-neitmann** [comment]
Not sure why this old check still pops up... My best guess would be because the most recent version of `devel` hasn't been merged into this branch yet. Let's see if similar issue arise on new PRs.

**Pull request merged**
