### PR TITLE
Add multiversion docs to main, fix linter workflow

### PR DESCRIPTION
**Pull request by dinakar29**
This is needed on main as well, immediately if possible to make it work as `main` is the intended default landing page.
This will fix the 404 on the admiral website.

Also fix the seemingly broken linter workflow.

### CODE REVIEW

**Comment by bms63** [comment]
lint is falling over
image

**Comment by bms63** [comment]
I'm a little confused - what is this update doing again for the pkgdown site?  Is this to help us preview the pre-release website before it goes live?

**Comment by dinakar29** [comment]
> I'm a little confused - what is this update doing again for the pkgdown site? Is this to help us preview the pre-release website before it goes live?

Yes

**Comment by bms63** [comment]
There is no lint error in the main branch.  I ran `lintr::lint_package()` and nothign comes up.  Perhaps issue in workflow??

**Comment by dinakar29** [comment]
> There is no lint error in the main branch. I ran `lintr::lint_package()` and nothign comes up. Perhaps issue in workflow??

Maybe. I updated the workflow to show the lint errors, if any so they're easy to spot.

**Comment by dinakar29** [comment]
I figured out another way to get the man pages up-to-date. Closing this PR.

**Pull request closed without merging**
