### PR TITLE
Closes #1640 add nominal time to create single dose dataset

### LINKED ISSUE #1640: Feature Request:  Add nominal time expansion option to `create_single_dose_dataset()`
### Feature Idea

For PK ADPC/ADNCA programming it would be helpful to add an option to expand nominal times (NFRLT) based on EXDOSFRQ in` create_single_dose_dataset()`. For example QD dose frequency would increment the NFRLT by 24 hours for each record in the expansion. This a fairly common issue in programming NCA or POPPK data.

### Relevant Input

```
   USUBJID     EXDOSFRQ NFRLT ASTDT      AENDT     
   <chr>       <chr>    <dbl> <date>     <date>    
 1 01-701-1028 QD           0 2013-07-19 2013-07-24
```

### Relevant Output

```
   USUBJID     EXDOSFRQ NFRLT ASTDT      AENDT     
   <chr>       <chr>    <dbl> <date>     <date>    
 1 01-701-1028 ONCE         0 2013-07-19 2013-07-19
 2 01-701-1028 ONCE        24 2013-07-20 2013-07-20
 3 01-701-1028 ONCE        48 2013-07-21 2013-07-21
 4 01-701-1028 ONCE        72 2013-07-22 2013-07-22
 5 01-701-1028 ONCE        96 2013-07-23 2013-07-23
 6 01-701-1028 ONCE       120 2013-07-24 2013-07-24
```

### Reproducible Example/Pseudo Code

Here is an example call
```
ex_expand <- ex %>%
  create_single_dose_dataset(
    dose_freq = EXDOSFRQ,
    start_date = ASTDT,
    start_datetime = ASTDTM,
    end_date = AENDT,
    end_datetime = AENDTM,
    lookup_table = dose_freq_lookup,
    lookup_column = CDISC_VALUE,
    nominal_time = NFRLT,
    keep_source_vars = vars(
      STUDYID, USUBJID, EXDOSFRQ, NFRLT, EXDOSE, EXTRT, 
      ASTDT, ASTDTM, AENDT, AENDTM
    )
  )
```

The parameter `nominal_time` could be added with the default as `NULL`.  Nothing would change with ordinary calling of the function, but if `nominal_time` is specified the value will be incremented by the hour difference between the output rows, e.g. 12, 24, 48 hours.  EXDOSFRQ values of QD, BID and QOD are most commonly seen for this, but others in `dose_freq_lookup` may be used.  Typically these are calculated in hours even if later converted to days.

### PR DESCRIPTION
**Pull request by jeffreyad**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by jeffreyad** [comment]
While updating `create_single_dose_dataset()` to add `nominal_time` I noticed an issue where times for "DAY" values if present were not updated even if the interval was less than a whole day, i.e. "BID", "TID" and "QID".  For example "Q12H" is being handled differently from "BID".  For a case with "BID" the start and end times are not updated even though two records are present for each day.

Here is an example:
```

data1 <- tribble(
  ~USUBJID, ~EXDOSFRQ, ~ASTDT, ~ASTDTM, ~AENDT, ~AENDTM,
  "P01", "BID", ymd("2021-01-01"), ymd_hms("2021-01-01 08:00:00"),
  ymd("2021-01-07"), ymd_hms("2021-01-07 20:00:00"),
  "P01", "BID", ymd("2021-01-08"), ymd_hms("2021-01-08 08:00:00"),
  ymd("2021-01-14"), ymd_hms("2021-01-14 20:00:00"),
  "P01", "BID", ymd("2021-01-15"), ymd_hms("2021-01-15 08:00:00"),
  ymd("2021-01-29"), ymd_hms("2021-01-29 20:00:00")
)

  USUBJID EXDOSFRQ ASTDT      ASTDTM              AENDT      AENDTM             
  <chr>   <chr>    <date>     <dttm>              <date>     <dttm>             
1 P01     BID      2021-01-01 2021-01-01 08:00:00 2021-01-07 2021-01-07 20:00:00
2 P01     BID      2021-01-08 2021-01-08 08:00:00 2021-01-14 2021-01-14 20:00:00
3 P01     BID      2021-01-15 2021-01-15 08:00:00 2021-01-29 2021-01-29 20:00:00


example1 <- data1 %>%
  create_single_dose_dataset(
    dose_freq = EXDOSFRQ,
    start_date = ASTDT,
    start_datetime = ASTDTM,
    end_date = AENDT,
    end_datetime = AENDTM,
    lookup_table = dose_freq_lookup,
    lookup_column = CDISC_VALUE,
    keep_source_vars = vars(
      USUBJID, EXDOSFRQ, ASTDT, ASTDTM, AENDT, AENDTM
    )
  )

  USUBJID EXDOSFRQ ASTDT      ASTDTM              AENDT      AENDTM             
   <chr>   <chr>    <date>     <dttm>              <date>     <dttm>             
 1 P01     ONCE     2021-01-01 2021-01-01 08:00:00 2021-01-01 2021-01-01 20:00:00
 2 P01     ONCE     2021-01-01 2021-01-01 08:00:00 2021-01-01 2021-01-01 20:00:00
 3 P01     ONCE     2021-01-02 2021-01-02 08:00:00 2021-01-02 2021-01-02 20:00:00
 4 P01     ONCE     2021-01-02 2021-01-02 08:00:00 2021-01-02 2021-01-02 20:00:00
 5 P01     ONCE     2021-01-03 2021-01-03 08:00:00 2021-01-03 2021-01-03 20:00:00
 6 P01     ONCE     2021-01-03 2021-01-03 08:00:00 2021-01-03 2021-01-03 20:00:00
 7 P01     ONCE     2021-01-04 2021-01-04 08:00:00 2021-01-04 2021-01-04 20:00:00
 8 P01     ONCE     2021-01-04 2021-01-04 08:00:00 2021-01-04 2021-01-04 20:00:00
 9 P01     ONCE     2021-01-05 2021-01-05 08:00:00 2021-01-05 2021-01-05 20:00:00
10 P01     ONCE     2021-01-05 2021-01-05 08:00:00 2021-01-05 2021-01-05 20:00:00
```

I updated to address this by changing the `CDISC_VALUE`  to  "HOUR" for values of "BID", "TID", "QID" and changing the `DOSE_COUNT` accordingly.  Here is the updated output:

```
   USUBJID EXDOSFRQ ASTDT      ASTDTM              AENDT      AENDTM             
   <chr>   <chr>    <date>     <dttm>              <date>     <dttm>             
 1 P01     ONCE     2021-01-01 2021-01-01 08:00:00 2021-01-01 2021-01-01 08:00:00
 2 P01     ONCE     2021-01-01 2021-01-01 20:00:00 2021-01-01 2021-01-01 20:00:00
 3 P01     ONCE     2021-01-02 2021-01-02 08:00:00 2021-01-02 2021-01-02 08:00:00
 4 P01     ONCE     2021-01-02 2021-01-02 20:00:00 2021-01-02 2021-01-02 20:00:00
 5 P01     ONCE     2021-01-03 2021-01-03 08:00:00 2021-01-03 2021-01-03 08:00:00
 6 P01     ONCE     2021-01-03 2021-01-03 20:00:00 2021-01-03 2021-01-03 20:00:00
 7 P01     ONCE     2021-01-04 2021-01-04 08:00:00 2021-01-04 2021-01-04 08:00:00
 8 P01     ONCE     2021-01-04 2021-01-04 20:00:00 2021-01-04 2021-01-04 20:00:00
 9 P01     ONCE     2021-01-05 2021-01-05 08:00:00 2021-01-05 2021-01-05 08:00:00
10 P01     ONCE     2021-01-05 2021-01-05 20:00:00 2021-01-05 2021-01-05 20:00:00
```

Here is an example for adding `nominal_time`:

```
data2 <- tribble(
  ~USUBJID, ~EXDOSFRQ, ~ASTDT, ~ASTDTM, ~AENDT, ~AENDTM, ~NFRLT,
  "P01", "BID", ymd("2021-01-01"), ymd_hms("2021-01-01 08:00:00"),
  ymd("2021-01-07"), ymd_hms("2021-01-07 20:00:00"), 0,
  "P01", "BID", ymd("2021-01-08"), ymd_hms("2021-01-08 08:00:00"),
  ymd("2021-01-14"), ymd_hms("2021-01-14 20:00:00"), 168,
  "P01", "BID", ymd("2021-01-15"), ymd_hms("2021-01-15 08:00:00"),
  ymd("2021-01-29"), ymd_hms("2021-01-29 20:00:00"), 336
)

  USUBJID EXDOSFRQ ASTDT      ASTDTM              AENDT      AENDTM              NFRLT
  <chr>   <chr>    <date>     <dttm>              <date>     <dttm>              <dbl>
1 P01     BID      2021-01-01 2021-01-01 08:00:00 2021-01-07 2021-01-07 20:00:00     0
2 P01     BID      2021-01-08 2021-01-08 08:00:00 2021-01-14 2021-01-14 20:00:00   168
3 P01     BID      2021-01-15 2021-01-15 08:00:00 2021-01-29 2021-01-29 20:00:00   336


example2 <- data2 %>%
  create_single_dose_dataset(
    dose_freq = EXDOSFRQ,
    start_date = ASTDT,
    start_datetime = ASTDTM,
    end_date = AENDT,
    end_datetime = AENDTM,
    lookup_table = dose_freq_lookup,
    lookup_column = CDISC_VALUE,
    nominal_time = NFRLT,
    keep_source_vars = vars(
      USUBJID, EXDOSFRQ, ASTDT, ASTDTM, AENDT, AENDTM, NFRLT
    )
  ) 

   USUBJID EXDOSFRQ ASTDT      ASTDTM              AENDT      AENDTM              NFRLT
   <chr>   <chr>    <date>     <dttm>              <date>     <dttm>              <dbl>
 1 P01     ONCE     2021-01-01 2021-01-01 08:00:00 2021-01-01 2021-01-01 08:00:00     0
 2 P01     ONCE     2021-01-01 2021-01-01 20:00:00 2021-01-01 2021-01-01 20:00:00    12
 3 P01     ONCE     2021-01-02 2021-01-02 08:00:00 2021-01-02 2021-01-02 08:00:00    24
 4 P01     ONCE     2021-01-02 2021-01-02 20:00:00 2021-01-02 2021-01-02 20:00:00    36
 5 P01     ONCE     2021-01-03 2021-01-03 08:00:00 2021-01-03 2021-01-03 08:00:00    48
 6 P01     ONCE     2021-01-03 2021-01-03 20:00:00 2021-01-03 2021-01-03 20:00:00    60
 7 P01     ONCE     2021-01-04 2021-01-04 08:00:00 2021-01-04 2021-01-04 08:00:00    72
 8 P01     ONCE     2021-01-04 2021-01-04 20:00:00 2021-01-04 2021-01-04 20:00:00    84
 9 P01     ONCE     2021-01-05 2021-01-05 08:00:00 2021-01-05 2021-01-05 08:00:00    96
10 P01     ONCE     2021-01-05 2021-01-05 20:00:00 2021-01-05 2021-01-05 20:00:00   108
```

**Comment by bms63** [comment]
Hi @jeffreyad are you able to fix the failing checks.  You can add `check_non` to the `globals.R` file and that shoudl fix these issues

**Review by bms63 — COMMENTED** [review]
I feel like we need additional tests for this and a blurb in the news for this issue.

**Comment by bms63** [comment]
@jeffreyad can you please add a test and make an entry in the news for us?

**Comment by jeffreyad** [comment]
> @jeffreyad can you please add a test and make an entry in the news for us?

@bms63 sure, will do.  Thanks

**Comment by bms63** [comment]
@jeffreyad Hey Jeff can you fix this and then we can merge in ASAP for the other adpc template.  The template PR is failing as it needs this update ( I think you told me this last week :) ) .

**Comment by jeffreyad** [comment]
> @jeffreyad Hey Jeff can you fix this and then we can merge in ASAP for the other adpc template. The template PR is failing as it needs this update ( I think you told me this last week :) ) .

Yes, done.  Thanks

**Pull request merged**
