### PR TITLE
Closes #1647 update compute duration units@devel

### LINKED ISSUE #1647: Feature Request:  Update `compute_duration` function to have "min" and "sec" for output units
### Feature Idea

Roche uses controlled terminology for any derivation with unit of duration, this controlled terminology is the same as used by SDTM variables.
For "seconds" the controlled terminology is "sec" and for "minutes" its "min".

### Relevant Input

For `compute_duration` for units of minutes the function outputs "minutes" and for seconds the function outputs "seconds"

### Relevant Output

For `compute_duration` for units of minutes the function should output "min" and for seconds the function should output "sec"

### Reproducible Example/Pseudo Code

_No response_

### PR DESCRIPTION
**Pull request by jeffreyad**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by jeffreyad** [comment]
It looked a similar change was needed for `derive_vars_duration()` to be consistent, so I updated that as well.  Based on previous discussion pharmaverse/admiraldev#122 it looks like `valid_time_units()` would not be updated since only the `out_unit` is affected.

**Comment by bms63** [comment]
I would think the `.R` files would also change as the `.Rd` are rendered from those files?

**Comment by jeffreyad** [comment]
> I would think the `.R` files would also change as the `.Rd` are rendered from those files?

@bms63 Should be in the first and second commits

**Review by bms63 — APPROVED** [review]
So weird GItHub only showed me the `.Rd` files and not the `.R` file changes.  Umm....

I fixed merged conflict.  This looks good to me!!

**Pull request merged**
