### PR TITLE
Closes #1074 change the example in derive var ontrtfl using ymdhm

### LINKED ISSUE #1074: derive_var_ontrtfl - issue with example
### What happened?

https://pharmaverse.github.io/admiral/reference/derive_var_ontrtfl.html shows in the examples: 

image

My best guess is `ymd("2020-01-02T12:00")` should be replaced with `ymd_hm("2020-01-02T12:00")`

### Session Information

NA

### Reproducible Example

NA

### PR DESCRIPTION
**Pull request by yli110-stat697**
close #1074 

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by bms63** [comment]
Not sure if this has been sanctioned by Rohce, but admiral really wants people to use the PR checklist template so that developers acknowledge that they have worked through each task before someone does a  Code Review - e.g.  styler checks, tests updated, documentation updated, no websites formatting issues.  This helps maintain a consistent code base and reduces time on reviews.

**Comment by yli110-stat697** [comment]
Hi @bms63 I have went through the checklist and applied what's suitable for my PR. Should I include the checklist in the PR conversation?

**Review by thomas-neitmann — CHANGES_REQUESTED** [review]
Please run `devtools::document()` once more such that the changes you've made to the example are reflected in the corresponding `.Rd` file.

**Comment by yli110-stat697** [comment]
close this PR as there's a new one to merge into `patch` to pick up hotfix

**Pull request closed without merging**
