### PR TITLE
#969 fix typos on function

### LINKED ISSUE #969: Documentation:  Typo in function naming
### Please select a category the issue is focused on?

User Guides

### Let us know where something needs a refresh or put your idea here!

There is a typo in: Creating ADSL ->Disposition Reason(s) (e.g. DCSREAS, DCSREASP)
[https://pharmaverse.github.io/admiral/articles/adsl.html#disposition_reason]

Function which is currently available in admiral is: [derive_var**s**_disposition_reason]

We have  's' missing in the vars in section which appears just after : 
The customized mapping function format_dcsreas() can now be passed to the main function:
derive_var_disposition_reason -> should be:  derive_vars_disposition_reason
with active link to the function

image

### PR DESCRIPTION
**Pull request by wqrena**
Close #969

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Review by thomas-neitmann — APPROVED** [review]
Thanks a lot!

**Comment by thomas-neitmann** [comment]
@wqrena Please tick off all entries in the issue comment checklist otherwise merging is blocked.

**Comment by wqrena** [comment]
@thomas-neitmann, I checked off all the tasks on the checklist, and merged the PR. Then I realized that you, as the reviewer, should be the one to merge the PR. Hope this is ok. 

In project, I have already moved the issue from backlog to review. 

Not sure if this means that I have completed the whole cycle for issue resolving. Please let me know If I missed any steps. Thanks!

**Comment by thomas-neitmann** [comment]
All good @wqrena! COngrats on getting your first PR merged 👏 

Once you open a PR you should move the issue to the "Review" column. Once merged please move it to "Sprint Done".

**Comment by wqrena** [comment]
@thomas-neitmann Thank you, Thomas! The issue was closed and moved to "Sprint Done".

**Pull request merged**
