### PR TITLE
Closes #1317 #1242 enhance derive param first event 

### LINKED ISSUE #1317: Feature Request: Enhance `derive_param_first_event()`
### Feature Idea

`derive_param_first_event()` should be enhanced such that the order can be specified and the last instead of the first event can be derived. I.e.,
- the `date_var` argument should be replaced by the `order` argument and
- the function should be renamed to `derive_param_extreme_event()` and the `mode` argument should be added.

### Relevant Input

_No response_

### Relevant Output

_No response_

### Reproducible Example/Pseudo Code

_No response_

### PR DESCRIPTION
**Pull request by sophie-gem**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by sophie-gem** [comment]
This PR is back on pending for now as I incorporate #1242 will hopefully be complete and ready approx 06NOV2022.

**Comment by rossfarrugia** [comment]
@sophie-gem how's things going with this PR? do you think we'll have it complete this week? sorry i know you've been away at phuse, its just we have the release upcoming in a couple of weeks and this one has knock on impacts to other admiral packages

**Comment by sophie-gem** [comment]
> @sophie-gem how's things going with this PR? do you think we'll have it complete this week? sorry i know you've been away at phuse, its just we have the release upcoming in a couple of weeks and this one has knock on impacts to other admiral packages. shout if you need any support!

Yep, should be able to get this complete by the end of this week. @bundfussr has kindly put in place the assertion function I need into `admiraldev` so hoping to be on the final stretch now.

**Comment by sophie-gem** [comment]
Hi @bundfussr, @rossfarrugia - `R CMD check` ran perfectly fine using `devtools::check()` within my local R session. However, for some reason, the three check workflows here have failed...I'll see if I can recreate the environments on my local laptop to start but if you have any ideas or other recommendations - please let me know. Many thanks!

**Comment by rossfarrugia** [comment]
@sophie-gem the branch should have the `@devel` suffix naming convention. you'll need to rename the branch and then re-open a new PR for this. it then means that dependencies like `admiraldev` have the latest `devel` branch taken in the CI workflows. at least that's my best guess! Stefan may have more ideas.

**Comment by sophie-gem** [comment]
Oh goodness, yes that'll be it exactly - I'm so sorry. I'm sure I've done this previously but I must have completely missed it this time! Thanks @rossfarrugia

**Pull request closed without merging**
