### PR TITLE
Closes #2244 fix_slice_derivation: add environment to params() and update sl…

### LINKED ISSUE #2244: Bug: `slice_derivation()` sometimes does not find objects when called from inside a function
### What happened?

If `slice_derivation()` is called inside a custom function, and some of the arguments of `slice_derivation()` are passed through the custom function, then depending on where these arguments appear in the slices, the function cannot "find them". See reproducible example for an example of this. I cannot tell from the outset which arrangements will cause errors and which will not. I briefly checked and couldn't replicate this behaviour with any other of the higher order functions but it would be good to check in more detail.

### Session Information

R version 4.2.2 Patched (2022-11-10 r83330)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.6 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/blas/libblas.so.3.9.0
LAPACK: /usr/lib/x86_64-linux-gnu/lapack/liblapack.so.3.9.0

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C              
 [3] LC_TIME=en_US.UTF-8        LC_COLLATE=en_US.UTF-8    
 [5] LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                 
 [9] LC_ADDRESS=C               LC_TELEPHONE=C            
[11] LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices datasets  utils     methods  
[7] base     

other attached packages:
[1] admiral_0.12.3.9007   dplyr_1.1.3          
[3] pharmaversesdtm_0.1.1 testthat_3.1.7       

loaded via a namespace (and not attached):
 [1] tidyselect_1.2.0      remotes_2.4.2        
 [3] purrr_1.0.2           vctrs_0.6.4          
 [5] generics_0.1.3        miniUI_0.1.1.1       
 [7] usethis_2.1.6         htmltools_0.5.4      
 [9] utf8_1.2.4            rlang_1.1.2          
[11] pkgbuild_1.4.0        urlchecker_1.0.1     
[13] later_1.3.0           pillar_1.9.0         
[15] glue_1.6.2            withr_2.5.2          
[17] admiraldev_0.5.0.9000 sessioninfo_1.2.2    
[19] lifecycle_1.0.4       stringr_1.5.1        
[21] devtools_2.4.5        htmlwidgets_1.6.1    
[23] memoise_2.0.1         callr_3.7.3          
[25] fastmap_1.1.1         httpuv_1.6.9         
[27] ps_1.7.2              fansi_1.0.5          
[29] Rcpp_1.0.10           xtable_1.8-4         
[31] renv_0.17.0           promises_1.2.0.1     
[33] cachem_1.0.7          desc_1.4.2           
[35] pkgload_1.3.2         mime_0.12            
[37] fs_1.6.1              brio_1.1.3           
[39] hms_1.1.3             digest_0.6.31        
[41] stringi_1.8.1         processx_3.8.0       
[43] shiny_1.7.4           rprojroot_2.0.3      
[45] cli_3.6.1             tools_4.2.2          
[47] magrittr_2.0.3        tibble_3.2.1         
[49] profvis_0.3.7         crayon_1.5.2         
[51] tidyr_1.3.0           pkgconfig_2.0.3      
[53] ellipsis_0.3.2        prettyunits_1.1.1    
[55] lubridate_1.9.3       timechange_0.2.0     
[57] rstudioapi_0.14       R6_2.5.1             
[59] compiler_4.2.2  

### Reproducible Example

```
library(admiral)
library(pharmaversesdtm)
library(dplyr, warn.conflicts = FALSE)

data("admiral_adsl")
data("ae")
data("ds")
data("ex")

adsl <- admiral_adsl

ds_ext <- derive_vars_dt(
  ds,
  dtc = DSSTDTC,
  new_vars_prefix = "DSST"
)

ex_ext <- ex %>%
  derive_vars_dtm(
    dtc = EXSTDTC,
    new_vars_prefix = "EXST"
  ) %>%
  derive_vars_dtm(
    dtc = EXENDTC,
    new_vars_prefix = "EXEN",
    time_imputation = "last"
  )

# Outside a function: this works
week_a = "WEEK 2"
week_b = "WEEK 24"

adsl %>% 
  slice_derivation(
    derivation = derive_vars_merged,
    args = params(
      new_vars = exprs(EOP01STT = "Completed"),
      missing_values = exprs(EOP01STT = "Ongoing"),
      by_vars = exprs(STUDYID, USUBJID)
    ),
    derivation_slice(
      filter = ACTARMCD %in% c("PBO"),
      args = params(
        dataset_add = ex_ext,
        filter_add = EXTRT %in% c("PLACEBO") & VISIT == week_a
      )
    ),
    derivation_slice(
      filter = TRUE,
      args = params(
        dataset_add = ex_ext,
        filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == c("WEEK 24") 
      )
    )
  )

adsl %>% 
  slice_derivation(
    derivation = derive_vars_merged,
    args = params(
      new_vars = exprs(EOP01STT = "Completed"),
      missing_values = exprs(EOP01STT = "Ongoing"),
      by_vars = exprs(STUDYID, USUBJID)
    ),
    derivation_slice(
      filter = ACTARMCD %in% c("PBO"),
      args = params(
        dataset_add = ex_ext,
        filter_add = EXTRT %in% c("PLACEBO") & VISIT == "WEEK 2"
      )
    ),
    derivation_slice(
      filter = TRUE,
      args = params(
        dataset_add = ex_ext,
        filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == week_b 
      )
    )
  )

# Inside a function: this also works
derive_eop01stt <- function(adsl_in, ex_in){
  
  adsl_in %>% 
    slice_derivation(
      derivation = derive_vars_merged,
      args = params(
        new_vars = exprs(EOP01STT = "Completed"),
        missing_values = exprs(EOP01STT = "Ongoing"),
        by_vars = exprs(STUDYID, USUBJID)
      ),
      derivation_slice(
        filter = ACTARMCD %in% c("PBO"),
        args = params(
          dataset_add = ex_in,
          filter_add = EXTRT %in% c("PLACEBO") & VISIT == "WEEK 2"
        )
      ),
      derivation_slice(
        filter = TRUE,
        args = params(
          dataset_add = ex_ext,
          filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == "WEEK 24"
        )
      )
    ) 
}

derive_eop01stt(adsl, ex_ext)

# Inside a function: with two parameters, this arrangement works
derive_eop01stt_1 <- function(adsl_in, ex_in, week){
  
  adsl_in %>% 
    slice_derivation(
      derivation = derive_vars_merged,
      args = params(
        new_vars = exprs(EOP01STT = "Completed"),
        missing_values = exprs(EOP01STT = "Ongoing"),
        by_vars = exprs(STUDYID, USUBJID)
      ),
      derivation_slice(
        filter = ACTARMCD %in% c("PBO"),
        args = params(
          dataset_add = ex_in,
          filter_add = EXTRT %in% c("PLACEBO") & VISIT == week
        )
      ),
      derivation_slice(
        filter = TRUE,
        args = params(
          dataset_add = ex_ext,
          filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == "WEEK 24"
        )
      )
    ) 
}

derive_eop01stt_1(adsl, ex_ext, "WEEK 2")

# Inside a function: with two parameters, this arrangement does not!
derive_eop01stt_2 <- function(adsl_in, ex_in, week){
  
  adsl_in %>% 
    slice_derivation(
      derivation = derive_vars_merged,
      args = params(
        new_vars = exprs(EOP01STT = "Completed"),
        missing_values = exprs(EOP01STT = "Ongoing"),
        by_vars = exprs(STUDYID, USUBJID)
      ),
      derivation_slice(
        filter = ACTARMCD %in% c("PBO"),
        args = params(
          dataset_add = ex_in,
          filter_add = EXTRT %in% c("PLACEBO") & VISIT == "WEEK 2"
        )
      ),
      derivation_slice(
        filter = TRUE,
        args = params(
          dataset_add = ex_ext,
          filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == week
        )
      )
    ) 
}

derive_eop01stt_2(adsl, ex_ext, "WEEK 24")
```

Error message:
```
Error in `filter()`:
ℹ In argument: `!(EXTRT %in% c("PLACEBO")) & VISIT ==
  week`.
Caused by error:
! object 'week' not found
```

### PR DESCRIPTION
**Pull request by bundfussr**
…ice_derivation() and call_derivation()

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF version of it to the same folder.
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers). A Developer Notes section is available in `NEWS.md` for tracking developer-facing issues.  
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by manciniedoardo** [comment]
@bundfussr thanks for working on this!
image

**Comment by manciniedoardo** [comment]
@bundfussr I tried rerunning this example from #2244 and I still get an error, do you know what's up?
```
library(admiral)
library(pharmaversesdtm)
library(dplyr, warn.conflicts = FALSE)

data("admiral_adsl")
data("ae")
data("ds")
data("ex")

adsl <- admiral_adsl

ds_ext <- derive_vars_dt(
  ds,
  dtc = DSSTDTC,
  new_vars_prefix = "DSST"
)

ex_ext <- ex %>%
  derive_vars_dtm(
    dtc = EXSTDTC,
    new_vars_prefix = "EXST"
  ) %>%
  derive_vars_dtm(
    dtc = EXENDTC,
    new_vars_prefix = "EXEN",
    time_imputation = "last"
  )

derive_eop01stt_2 <- function(adsl_in, ex_in, week){
  
  adsl_in %>% 
    slice_derivation(
      derivation = derive_vars_merged,
      args = params(
        new_vars = exprs(EOP01STT = "Completed"),
        missing_values = exprs(EOP01STT = "Ongoing"),
        by_vars = exprs(STUDYID, USUBJID)
      ),
      derivation_slice(
        filter = ACTARMCD %in% c("PBO"),
        args = params(
          dataset_add = ex_in,
          filter_add = EXTRT %in% c("PLACEBO") & VISIT == "WEEK 2"
        )
      ),
      derivation_slice(
        filter = TRUE,
        args = params(
          dataset_add = ex_ext,
          filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == week
        )
      )
    ) 
}

derive_eop01stt_2(adsl, ex_ext, "WEEK 24")
```
Returns:
```
Error in `filter()`:
ℹ In argument: `!(EXTRT %in% c("PLACEBO")) & VISIT == week`.
Caused by error:
! object 'week' not found
```

**Comment by bundfussr** [comment]
It should be 
```
filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == !!week
```
instead of 
```
filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == week
```
because `week` is not a column of the dataset.

By the way, it should also be
```
filter = ACTARMCD %in% c("Pbo"),
```
instead of
```
filter = ACTARMCD %in% c("PBO"),
```
Otherwise, no records match the condition. This explains the "strange" behavior that the order matters.

**Review by bms63 — COMMENTED** [review]
I’ve been a bit confused about this bug.

Do we need to tell the user that the expected object isn’t available in their current environment.  I’m confused when this would NOT happen and why this couldn’t find the objects in the first place.

**Comment by ddsjoberg** [comment]
If we make the below a quosure, it will have the env attached and should be able to evaluate without the `!!week`. We should probably aim to have our expression syntax match that of `dplyr::filter()` (and many many other functions too). Sorry I don't have the bandwidth to look at these details right now.

> filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == week

**Comment by manciniedoardo** [comment]
Thanks @bundfussr!
> because `week` is not a column of the dataset.
Lol, I fell for the same [pitfall](https://pharmaverse.github.io/admiral/dev/articles/concepts_conventions.html#forgetting-that-expressions-must-be-evaluable-in-the-dataset) I wrote about a few weeks ago!

**Comment by bundfussr** [comment]
> If we make the below a quosure, it will have the env attached and should be able to evaluate without the `!!week`. We should probably aim to have our expression syntax match that of `dplyr::filter()` (and many many other functions too). Sorry I don't have the bandwidth to look at these details right now.
> 
> > filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == week

Using quosures for `filter` arguments is a major change (for us and the users). I wouldn't do it now because we want to release soon.
I think the `dplyr` and other functions behave differently because they are more focused on interactive calls. There the ambiguity introduced by quosures is acceptable. In our context I would prefer to be more strict and avoid ambiguities. If we use quosures, `filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == week` would work in most cases but if the dataset contains the `week` variable, it would fail or produce wrong results. So even if we use quosures, we should use `filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == .env$week` or `filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == !!week` (as recommended in [Preventing Collisions](https://rlang.r-lib.org/reference/topic-data-mask-ambiguity.html#preventing-collisions)). The advantage of our approach is that the code fails immediately if you forget the `!!`. If quosures are used and you forget the `.env$` or `!!`, it fails later or produces wrong results. In this case, it is much more difficult to determine the cause of the problem.
Therefore I would not change our approach.

**Comment by ddsjoberg** [comment]
We dont need to request users pass quosures, so there should be no change for them. Rather we capture what they pass as a quosure, so we have the appropriate env to evaluate it in.

it will be confusing to users why code like this works: `dplyr::filter(filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == week)` But the same code does not work for filtering in admiral.

**Comment by ddsjoberg** [comment]
> The users don't need to pass quosures but they should use `filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == !!week` instead of `filter_add = !(EXTRT %in% c("PLACEBO")) & VISIT == week` (unless they are just playing around in the console).

That great we're on the same page about not requesting users pass proper quosures. 👯 

But requiring that users include `!!week`, when it's not required in `dplyr::filter()` will certainly be a pain point.

**Comment by bms63** [comment]
@manciniedoardo if this satisfies your requirements then can your approve and merge in?

@bundfussr apologies for my ignorance and not being a help here.   my only concern is that if this is a bug that a user can create - should we be testing that the bug no longer appears or are we confident that with the updates this situation should no longer happen...Like is this an edge case that we need to cover and give feedback to the user through error messaging or is this the case of our function just not working as intended.

**Comment by bundfussr** [comment]
> @bundfussr apologies for my ignorance and not being a help here. my only concern is that if this is a bug that a user can create - should we be testing that the bug no longer appears or are we confident that with the updates this situation should no longer happen...Like is this an edge case that we need to cover and give feedback to the user through error messaging or is this the case of our function just not working as intended.

@bms63 , I have added a unit for the case where it didn't work before (when `slice_derivation()` is called in a function and an object defined in the function is passed to one of the `params()` objects).

**Review by manciniedoardo — APPROVED** [review]

**Pull request merged**
