### PR TITLE
Closes #2593 feat: Add my_first_fcn to welcome new users

### PR DESCRIPTION
**Pull request by luenhchang**
- Create new function my_first_fcn()
- Add corresponding test
- Resolves #1839

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [ ] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF and a PNG version of it to the same folder. (The PNG version can be created by taking a screenshot of the PDF version.)
- [ ] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers). A Developer Notes section is available in `NEWS.md` for tracking developer-facing issues.  
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by bms63** [comment]
Hi @luenhchang welcome!!  Can you fix the documentation action please?

It is good to work through the checklist - let me know if you have any questions.  Here is our programming strategy - if you are looking for some lite reading this weekend :) https://pharmaverse.github.io/admiraldev/dev/articles/programming_strategy.htm

**Comment by bms63** [comment]
Please put in a NEws.md entry as well to test things out :)

**Comment by luenhchang** [comment]
> Hi @luenhchang welcome!! Can you fix the documentation action please?
> 
> It is good to work through the checklist - let me know if you have any questions. Here is our programming strategy - if you are looking for some lite reading this weekend :) https://pharmaverse.github.io/admiraldev/dev/articles/programming_strategy.htm

Hi @bms63
Can you let me know what documentation action to be fixed? The link https://pharmaverse.github.io/admiraldev/dev/articles/programming_strategy.htm is not working

Thanks

**Comment by luenhchang** [comment]
> Please put in a NEws.md entry as well to test things out :)

Hi @bms63,

I’ve reviewed the NEWS.md file in admiral-development/admiral and noticed that the entries seem to follow a specific format. Could you please point me to any guidelines or documentation outlining this format?

Thank you!

**Comment by bms63** [comment]
Not a lot of guidance on making a News entry.

We always link the issue at the end of the entry e.g.
* Fixed bug for admiral_fcn() where users doing this caused this (#1814)

Be sure to place the entry in the relevant sections:  New Features, Updates of Existing Functions, Breaking Changes, Documentation

We have a little hidden dev section for documenting big changes or things we want to track.

Keep it short and informative.  The News.md can get quite long if we are not careful.

**Comment by bms63** [comment]
> > Hi @luenhchang welcome!! Can you fix the documentation action please?
> > It is good to work through the checklist - let me know if you have any questions. Here is our programming strategy - if you are looking for some lite reading this weekend :) https://pharmaverse.github.io/admiraldev/dev/articles/programming_strategy.htm
> 
> Hi @bms63 Can you let me know what documentation action to be fixed? The link https://pharmaverse.github.io/admiraldev/dev/articles/programming_strategy.htm is not working
> 
> Thanks


this one
image
use `devtools::document()`

**Comment by bms63** [comment]
Hi @luenhchang - going to close this PR EOD unless I hear from you. Can always reopen when you have time to complete again.

**Comment by luenhchang** [comment]
@bms63 
Just to confirm, I have made the following changes in this PR:

1. Updated the message in R/my_first_fcn.R from "Welcome to admiral!" to "Welcome to the admiral family!".
2. The associated .Rd documentation in man/my_first_fcn.Rd has been updated accordingly.

**Comment by bms63** [comment]
Yay!  now to fix the spelling issue!  Be sure to review these CIs each time you push up a change while in a Pull Request 
image

**Comment by luenhchang** [comment]
@bms63
I have added the word "onboarding" to the inst/WORDLIST file and pushed the changes to the branch. Please let me know if anything else is needed or if you'd like me to make further adjustments.

**Comment by bms63** [comment]
Looks awesome!  How do you feel about working on this issue https://github.com/pharmaverse/admiral/issues/2551

It is just restructuring the files so easier to find?  Will help get you familiar with admiral conventions and where things are located.

**Comment by luenhchang** [comment]
> Looks awesome! How do you feel about working on this issue #2551
> 
> It is just restructuring the files so easier to find? Will help get you familiar with admiral conventions and where things are located.

@bms63
I’d be happy to give it a try! Should I coordinate with jeffreyad, since it looks like he self-assigned the issue about 4 hours after your comment?

**Comment by bms63** [comment]
Yes!  @jeffreyad could @luenhchang take over your issue #2551 ?

**Comment by jeffreyad** [comment]
> Yes! @jeffreyad could @luenhchang take over your issue #2551 ?

Sure! I haven't done anything for that yet

**Pull request closed without merging**
