### PR TITLE
#1017 Documentation correction

### PR DESCRIPTION
**Pull request by JMcGavigan32**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Comment by JMcGavigan32** [comment]
Hi @bms63,

So the most recent branch is `1017_Update_Docs`. I branched from `devel` and have included the updates for both `derive_var_trtsdtm` and `derive_var_trtedtm`. I also made sure to put the Issue number at the beginning of the commit.

The branch we need to delete is named `1017_Update_Documentation`.

Hope this is all correct, let me know if there's anything else I need to do!

Jack

**Comment by bms63** [comment]
Hi Jack,

I closed the PR and deleted that branch.

**Comment by JMcGavigan32** [comment]
Hi Ben,
Sorry I didn't actually do that at the time, wrongly assumed it wouldn't be relevant for such a small update! I'm getting the following ERROR when the console starts to build the .Rmd files:

`\- Building articles -----------------------------------------------------------
Reading 'vignettes/admiral.Rmd'
Error : Failed to render RMarkdown`

**Comment by bms63** [comment]
> Hi Ben, Sorry I didn't actually do that at the time, wrongly assumed it wouldn't be relevant for such a small update! I'm getting the following ERROR when the console starts to build the .Rmd files:
> 
> `\- Building articles ----------------------------------------------------------- Reading 'vignettes/admiral.Rmd' Error : Failed to render RMarkdown`

You might need to either be off the VPN or need to see if you have pkgdown installed.  @amsmith214 - any insights?

**Comment by JMcGavigan32** [comment]
`pkgdown` is installed and I'm off VPN. I am getting this warning as well if clears anything up: `[WARNING] Deprecated: markdown_github. Use gfm instead.`

**Comment by bms63** [comment]
> `pkgdown` is installed and I'm off VPN. I am getting this warning as well if clears anything up: `[WARNING] Deprecated: markdown_github. Use gfm instead.`

The detracted warning is okay.  The vignettes should build.  See if Andrew replies or maybe @esimms999-gsk or @teckla-gsk  know the workaround?

**Comment by bms63** [comment]
Hi Jack,

I pull your branch and re-ran the packagedown site.  All looks good to me.  We can say this is done now.  If you are interested in doing 20% FTE on admiral (which we need), then lets talk about RStudio Cloud option to work on this project rather than Desktop R.

image

image

**Review by bms63 — APPROVED** [review]
Nicely done!

**Comment by JMcGavigan32** [comment]
Awesome, thanks for all your help with that @bms63! First Issue complete. Will message you tomorrow RE: Cloud R Studio.

**Pull request merged**
