### PR TITLE
In derive_advs_params.R:

### PR DESCRIPTION
**Pull request by esimms999-gsk**
derive_param_bsa: in Roxygen examples, added set_values_to in order to assign PARAM and AVALU. Previously, these were coming out as NA.

For derive_param_map, _bmi: in Roxygen examples, added AVALU to set_values_to. Previously, AVALU was coming out as NA.

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Review by thomas-neitmann — COMMENTED** [review]
I wonder if we should rather remove `AVALU` completely. It's not a CDISC variable after all... Any thoughts @pharmaverse/admiral-devs?

**Comment by thomas-neitmann** [comment]
As far as I know `AVALU` is something we use at Roche but it's not actually in the CDISC standard. Is that correct @millerg23?

**Comment by millerg23** [comment]
Yeah I was surprised AVALU was not a CDISC derivation, and yes we use it in Roche. However, the unit is in PARAM value, so I guess CDISC see it as duplication of information.

**Comment by esimms999-gsk** [comment]
OK. But do we really want it removed from the examples?

**Comment by thomas-neitmann** [comment]
I'll leave that decision to you 😉

**Comment by millerg23** [comment]
I thought we agreed we'd only have CDISC derivations in the Examples. Do we need AVALU?

**Comment by thomas-neitmann** [comment]
Good point @millerg23!

**Comment by esimms999-gsk** [comment]
Removed AVALU from roxygen examples for derive_param_bmi, derive_param_bsa, derive_param_map.

**Comment by esimms999-gsk** [comment]
I am unsure why the R-CMD-check is failing
derive_vars_merged_github_check
.

**Review by thomas-neitmann — APPROVED** [review]
Thank you!

**Pull request merged**
