### PR TITLE
CLOSE #1423 variable label@devel

### LINKED ISSUE #1423: Feature Request:  Automate assigning variable labels
### Feature Idea

In current template code, the newly created variables do not have labels assigned to them. Bearing in mind the esub-readiness principle, this should be added to the template code. Moreover, instead of manually assigning labels, there should be a way to automate this process by directly reading spec.

### Relevant Input

_No response_

### Relevant Output

_No response_

### Reproducible Example/Pseudo Code

_No response_

### PR DESCRIPTION
**Pull request by w316liu**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by bms63** [comment]
Thanks @w316liu!  What about adding your text and the extra I have highlighted to the end of each dataset walkthrough vignette?  @pharmaverse/admiral  Any thoughts?

image

image

**Comment by w316liu** [comment]
I agree that we should add this whole section to each ADaM types. But another point to consider is that there is only ADSL in the E2E example (the "Applying metadata" section is the same). So do we consider to make it a standalone Rmd to avoid duplicate work?

**Comment by thomas-neitmann** [comment]
> But another point to consider is that there is only ADSL in the E2E example (the "Applying metadata" section is the same)

There are plans to add further E2E examples for datasets other than ADSL.

**Comment by bms63** [comment]
I say lets add to the end of each dataset vignette then.  Driving folks to our e2e examples I think it important even if we only have ADSL at the moment.

**Comment by w316liu** [comment]
Sounds good to me. I can add to the rest vignetts.

**Comment by w316liu** [comment]
Updated the rest datasets vignettes. 
@bms63 can you take a look at the checking error? Not sure if it applies to this merge.

**Comment by bms63** [comment]
@w316liu the 3.6 failing check?

**Comment by w316liu** [comment]
Yes. Do you have any suggestion?

**Comment by bms63** [comment]
That is okay to ignore

**Review by bms63 — APPROVED** [review]
Love it!!  Thanks for following through on this one!!

**Pull request merged**
