### PR TITLE
#954 Refining typos

### PR DESCRIPTION
**Pull request by bms63**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Comment by bms63** [comment]
Hey all.  I merged this into devel and spotted some typos and formatting issues after looking it over.  I fixed up.  Can you approve and I will merge my udpates into devel??

Do you think we should ask review from our core developers?  I don't want to redo it or really get more cooks in the kitchen, but nice for people to know what they have signed on to!

**Review by rossfarrugia — APPROVED** [review]

**Comment by rossfarrugia** [comment]
@bms63 i shared the original PR on our dev slack April 11th so i'm happy everyone has had chance to review and comment. i plan to talk through and raise more awareness at the community meeting next week

**Comment by bms63** [comment]
Hey @thomas-neitmann .  I'm going to merge in this PR as it was just an update to the Readme.  All the checks are going to fail until we update to the new `admiral_ `prefix stuff for `admiraltest`.  What do you think?

**Comment by koegerr** [comment]
@bms63 and @thomas-neitmann can this be fixed as a priority. Would be nice to get it out by the 15th May

**Review by koegerr — APPROVED** [review]

**Review by koegerr — APPROVED** [review]

**Comment by bms63** [comment]
I think we can move this into `devel` branch as it doesn't touch any code.  The rename of the datasets is causing everything to break down at the moment.

**Comment by bms63** [comment]
@thomas-neitmann can we merge this into `devel`?

**Comment by koegerr** [comment]
yes, fine by me. Since it is just the vignettes

**Pull request merged**
