### PR TITLE
Closes #2446 Cleaned up and alphabetized admiral-pacakges.R 

### LINKED ISSUE #2446: General Issue: Clean up and alphabetize `admiral-pacakges.R`
The https://github.com/pharmaverse/admiral/blob/main/R/admiral-package.R is getting a bit messy.  There are duplicated packages with one or two functions listed, which should be consolidated.  The file is also a bit hard to read as nothing is alphabetize.

image

Pervious discussion
_Originally posted by @bms63 in https://github.com/pharmaverse/admiral/pull/2362#discussion_r1613492532_

Definition of Done

- [ ] Consolidate duplicated packages into one
- [ ] Alphabetize functions

Quick win for anyone interested!  @pharmaverse/admiral @pharmaverse/admiral_comm

### PR DESCRIPTION
**Pull request by gg106046**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [ ] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF version of it to the same folder.
- [ ] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers). A Developer Notes section is available in `NEWS.md` for tracking developer-facing issues.  
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by StefanThoma** [comment]
Hi @bms63 
Is it possible you did not run devtools::document()?
When I run it on my updated from master branch I get a lot of man/ files with just ordered lines.

**Comment by bms63** [comment]
> Hi @bms63 Is it possible you did not run devtools::document()? When I run it on my updated from master branch I get a lot of man/ files with just ordered lines.

The check passed for documentation.  I'm not sure what you mean by ordered lines - screenshot?

Are you using the correct roxygen version in the DESCRIPTION?

**Comment by StefanThoma** [comment]
Ah no I think I am not using the correct version, let me double check.

**Comment by StefanThoma** [comment]
You are right, all good :)

**Pull request merged**
