### PR TITLE
#743 updated documentation for min_dates and max_dates to clarify tha…

### PR DESCRIPTION
**Pull request by VD766**
…t date or date-time object is expected.

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Comment by VD766** [comment]
Some of the items in the check list do not apply as this is an update to the header.

**Comment by bms63** [comment]
> Some of the items in the check list do not apply as this is an update to the header.

That is fine - just check off even if they don't apply.

**Comment by VD766** [comment]
@bms63  All my checks are passing except R-CMD (3.5)

**Comment by bms63** [comment]
You need to run `devtools::document() `so the .Rd file gets updated as well.  Are you able to check the packagedown site to make sure things line up okay.  I think Jack was having issues with Desktop R.

**Comment by bms63** [comment]
image

You only need to do #743 Updated...

**Review by bundfussr — CHANGES_REQUESTED** [review]
Please update the `analysis_date` and `dose_date` parameter in the `derive_var_last_dose_*()` functions.

**Comment by bms63** [comment]
Hi Vishnu,  Can you merge devel into  your branch.  We no longer support 3.5.  Is there anything that needs to be clarified to finalize this PR?

**Comment by VD766** [comment]
@bundfussr  - I made the updates to analysis_date and dose_date params within the derive_vars_last_dose functions.

**Review by bundfussr — APPROVED** [review]

**Comment by bundfussr** [comment]
@bms63 , could you merge this PR using admin privileges?

**Review by teckla-gsk — APPROVED** [review]

**Comment by bms63** [comment]
Any ideas on why latest release is failing?  I can merge it, just want to know if anyone has any ideas??

**Comment by bundfussr** [comment]
Most likely the note is issued because in the DESCRIPTION file `hms` is listed in the `Imports:` section but in admiral-package.R nothing from `hms` is imported. We need this dependency because in hms.R we use the `hms` package. I am not sure if we still need hms.R. It looks like a work-around for older package versions.

I think we need to improve our documentation. Also "internal" functions should be documented. If any work-arounds are implemented it should be stated why this was done and when the work-around can be removed.

**Comment by bundfussr** [comment]
The note is regarding the `hms` package and not regarding the `hms()` function from the `lubridate` package.

I agree with Gordon that the issue should be resolved once https://github.com/pharmaverse/admiral/pull/1078 is merged.

**Pull request merged**
