### PR TITLE
#1059 - extra example

### LINKED ISSUE #1059: Documentation:  Add a simpler example for derive_var_basetype
### Please select a category the issue is focused on?

Function Documentation

### Let us know where something needs a refresh or put your idea here!

Add a simpler example for derive_var_basetype using a real-life common example.

### PR DESCRIPTION
**Pull request by rossfarrugia**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

closes #1059

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@bundfussr this was the simple example i wanted to add for BASETYPE, i.e. case where every param/record needs to use one baseline for LAST and one for WORST. i personally found the example given more complex than the more common needs for this variable, so it took me a while to grasp, whereas i think with the simple example people will get it quicker.

can you take a look and see what you think? happy to go with any alternative you can think of besides the `!is.na(USUBJID)` piece

**Review by bundfussr — CHANGES_REQUESTED** [review]
Looks good except of the work-around. I would use `TRUE` instead of `!is.na(USUBJID)`. To make this work you need to replace `is.language` with `~ is.language(.x) | is.logical(.x)` in line 755 of assertions.R.

**Comment by bundfussr** [comment]
@thomas-neitmann , here is another PR where the required 3.6 R-CMD check does not run. Any idea what is going wrong?

**Comment by rossfarrugia** [comment]
i used admin rights to merge and Thomas can check when back from holiday or resolve later when merging with main for the release.

**Pull request merged**
