### PR TITLE
Closes #2342 Clean up easy if() and else if() code chunks in datetime/date codebase

### LINKED ISSUE #2342: Clean up easy `if()` and `else if()` code chunks in datetime/date codebase
To reduce cyclomatic complexity in the datetime/date functions, there are two functions:
1. `get_imputation_target_date()`
2. `get_imputation_target_time()` 
that can be easily compressed into a `case_when()` statement reducing the complexity and making code more ledgible. Anywhere else that is found to be an "easy" swap/replacement can be applied too

Defintion of done:
Research and apply changes to respective functions and anywhere else that seems that appropriate

### PR DESCRIPTION
**Pull request by Fanny-Gautier**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF version of it to the same folder.
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by Fanny-Gautier** [comment]
How can I address the following warning while running `devtools::check()` ?
image

**Comment by bms63** [comment]
> How can I address the following warning while running `devtools::check()` ? image

You don't need to worry about the qpdf stuff. ...but if you want to get rid of it...I believe installing the package will help https://rbasics.org/guides/how-to-use-the-qpdf-package-in-r/

Let me know if it works!!

**Comment by Fanny-Gautier** [comment]
> > How can I address the following warning while running `devtools::check()` ? image
> 
> You don't need to worry about the qpdf stuff. ...but if you want to get rid of it...I believe installing the package will help https://rbasics.org/guides/how-to-use-the-qpdf-package-in-r/
> 
> Let me know if it works!!

I have installed the package, but it does not change anything, I still face the warning. I'll proceed with the PR with this remaining warning.
image

**Comment by Fanny-Gautier** [comment]
It looks like derive_date_vars.R does not exist anymore and updates must be implemented in derive_vars_dt_dtm_utils.R instead. Could you please confirm the same and how can I resolve the conflicts with the non-existing file derive_date_vars.R ?
image
Thanks.

**Comment by Fanny-Gautier** [comment]
@bms63 Can I simply delete that branch (2342_clean_up_easy_if_and_else_if_code_datetimedate) without proceeding with the PR, as the new file to update is anyway not on that branch ?

**Comment by bms63** [comment]
> @bms63 Can I simply delete that branch (2342_clean_up_easy_if_and_else_if_code_datetimedate) without proceeding with the PR, as the new file to update is anyway not on that branch ?

Yes!! that is easiest and quickest solution!!

Although fixing the merge conflicts at the command line is a nice exercise especially for something so minor if you have not done it before!!  :) Choose your adventure :)

**Comment by Fanny-Gautier** [comment]
> > @bms63 Can I simply delete that branch (2342_clean_up_easy_if_and_else_if_code_datetimedate) without proceeding with the PR, as the new file to update is anyway not on that branch ?
> 
> Yes!! that is easiest and quickest solution!!
> 
> Although fixing the merge conflicts at the command line is a nice exercise especially for something so minor if you have not done it before!! :) Choose your adventure :)

I tried to with the github [doc help](https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/addressing-merge-conflicts/resolving-a-merge-conflict-using-the-command-line#removed-file-merge-conflicts), but I was expecting to see that there was a conflict... 
image
I am not sure here how to proceed to see the conflicts.

**Comment by Fanny-Gautier** [comment]
@bms63 thanks for sharing the commands, doing great with your help.
image

Do I have to commit all these updates ?
image

**Comment by bms63** [comment]
Nice!!  Now you can update those files.  Another PR removing and adding files can cause a lot of issues while you are working on the same thing!!

When you have a PR open - it is good to check if there are any latest updates that you can merge into your branch.  Just make sure you pull them down one you click this button 

image

**Review by zdz2101 — APPROVED** [review]
@bms63 @millerg23 LGTM do yall have any thoughts?

**Pull request merged**
