### PR TITLE
907 imputation vignette updates

### LINKED ISSUE #907: Update Date and Time Imputation Vignette with preserve and ignore_seconds examples
The functions showcased in this vignette have been updated to have preserve and ignore seconds arguments.  #589 #592   This issue will be done when examples showcasing those updated arguments are presented.

### PR DESCRIPTION
**Pull request by rossfarrugia**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

closes #907

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@bms63 would you have time to review these imputation vignette updates please as they're all closely linked to updates you made to the functions so you'd understand best if i've hit the mark or not.

**Comment by bms63** [comment]
Hi @rossfarrugia Can you merge devel into this and branch and see if it fixes the issue?

**Comment by rossfarrugia** [comment]
@bms63 will do (likely after PHUSE)

**Comment by rossfarrugia** [comment]
@bms63 when i now run:
```
dates <- c(
  "2019-02",
  "2019",
  "2019---01"
)
impute_dtc(
  dates,
  date_imputation = "mid",
  time_imputation = "00:00:00",
  preserve = FALSE
)
```
i get:
``` 
[1] "2019-06-30T00:00:00" "2019-06-30T00:00:00" "2019-06-30T00:00:00"
```
Shouldn't this be:
``` 
[1] "2019-02-15T00:00:00" "2019-06-30T00:00:00" "2019-06-30T00:00:00"
```
???

p.s. how are the unit tests not picking these up??

**Comment by bundfussr** [comment]
@rossfarrugia , good catch. I think the issue is in line 213 of `derive_date_vars.R`.

Should we fix it within this PR?

**Comment by rossfarrugia** [comment]
sure. happy if you or @bms63 want to make commits here to fix it to save a separate PR, but can we also get a unit test added to cover these cases so we're covered for future?

**Comment by bundfussr** [comment]
@rossfarrugia , @bms63 , I have committed a fix. We had a unit test but it was wrong. I have corrected it.

**Review by bms63 — APPROVED** [review]
Thanks all for fixing this issue.

**Comment by rossfarrugia** [comment]
thanks both - i'll merge this one with admin rights as its the usual current CMDcheck issues due to the admiraltest updates

**Pull request merged**
