### PR TITLE
Closes #1451 Increased test coverage for derive_param_exposure

### LINKED ISSUE #1451: General Issue: Increase test coverage for `derive_param_expsure.R`
### Background Information

Increase test coverage for `derive_param_exposure.R`

This section of the function does not have any test coverage.  You can get this report by running `devtools::test_coverage()`

image

### Definition of Done

A new test is written in `test-derive_param_expsure.R` that closes the gap in test coverage

### PR DESCRIPTION
**Pull request by DeclanHodges**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

Increased test coverage for derive_param_exposure, by adding tests for the scenario when the input dataset only contains AxxDT variables.

### CODE REVIEW

**Comment by bms63** [comment]
Hey @DeclanHodges  Please click Update branch to get latest updates from devel.  Also check into the "Details" of failing Man Pages test to get advice on how to fix that one.

image

**Review by bms63 — COMMENTED** [review]
Did you run `devtools::test_coverage()` to double check that these tests cover all testable lines?

**Review by bms63 — COMMENTED** [review]
Also use the addin to help with formatting the test - 

image

https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#addin-admiraldevformat_test_that_file

Also!! Many thanks for working on this!!

**Comment by DeclanHodges** [comment]
Hi Ben @bms63,
Thanks for reviewing this. I'm having some issues with the formatting addin and the man pages / roxygen check - I will have another look at these tomorrow. Also, I have checked the new test coverage - it comes to 100% now:
image

**Review by bms63 — APPROVED** [review]
Nicely done Declan!  And congrats on your first PR into admiral!!

**Pull request merged**
