### PR TITLE
Revert "Add multi-version docs job"

### PR DESCRIPTION
**Pull request by dinakar29**
Reverts pharmaverse/admiral#1245

### CODE REVIEW

**Review by bundfussr — APPROVED** [review]

**Review by bms63 — APPROVED** [review]
Thanks!  I like the idea of using admiraltemplate and admiralonco to test this out and get it right.

**Comment by bms63** [comment]
Umm...did something get updated in devel that is causing the link checker to fail now?  I thought none of the PRs made it in

**Comment by thomas-neitmann** [comment]
Everything fails with "Network error" so I assume it's not related to the links themselves.

**Comment by bms63** [comment]
This needs to go to `main` and not `devel` so the website republishes

**Comment by dinakar29** [comment]
This just needs to go into `devel`, I'll clean up the `gh-pages` branch after.

**Pull request merged**
