### PR TITLE
closes #1839 dummy function created

### PR DESCRIPTION
**Pull request by Pierre-Wallet**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF version of it to the same folder.
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by Pierre-Wallet** [comment]
branch can be deleted

**Comment by bms63** [comment]
- [ ] oh and run devtools::document()
- [ ] can you build the pkgdown site locally
- [ ] @main is from a bygone era - no need to include for admiral projects

**Comment by Pierre-Wallet** [comment]
Hi @bms63 ,

I was not able to build the site due to this error ( I ran pkgdown::build_site(override = list(destination = "docs")):

Error: 
! in callr subprocess.
Caused by error in `check_missing_topics(rows, pkg)`:
! All topics must be included in reference index
✖ Missing topics: hello_admiral
ℹ Either add to _pkgdown.yml or use @keywords internal
ℹ See `$stdout` for standard output.
Type .Last.error to see the more details.

**Comment by bms63** [comment]
> Hi @bms63 ,
> 
> I was able to build the site ( I ran pkgdown::build_site(override = list(destination = "docs")) but I am not sure if it is the correct approach.
> 
> The reference tab CSS does not apply yet.
> 
> I had many issues to build it due to missing dependencies (pharmaversesdtm, reactable, diffdf...). Maybe to mention it somewhere that the Suggests packages are required for the package developer.
> 
> Bests, Pierre.

Thanks Pierre.  I usualyl recommend to have folks do `devtools::installl_dev_deps(dependencies = TRUE)` to get everything.  @zdz2101, @manciniedoardo @rossfarrugia something to put in our onboarding toolbox and maybe the video?

**Comment by bms63** [comment]
See if you can fix the spelling action as well.  :) Then you are admiral pro!!

**Comment by Pierre-Wallet** [comment]
> See if you can fix the spelling action as well. :) Then you are admiral pro!!

Seems that the pipeline is in green now.
An admiral pro? Not yet but let's work on it.

Good to be part of the team.

**Comment by sheramin** [comment]
> > See if you can fix the spelling action as well. :) Then you are admiral pro!!
> 
> Seems that the pipeline is in green now. An admiral pro? Not yet but let's work on it.
> 
> Good to be part of the team.

**Comment by sheramin** [comment]
> Hi @bms63 ,
> 
> I was able to build the site ( I ran pkgdown::build_site(override = list(destination = "docs")) but I am not sure if it is the correct approach.
> 
> The reference tab CSS does not apply yet.
> 
> I had many issues to build it due to missing dependencies (pharmaversesdtm, reactable, diffdf...). Maybe to mention it somewhere that the Suggests packages are required for the package developer.
> 
> Bests, Pierre.

Hi @Pierre-Wallet 
It looks like I have a similar issue. Can you recall what dependencies you had to install (I've installed those that you mentioned, but I think there are more)?

(Sorry I mistakenly closed another thread, hopefully it's only on my side)

Amin

**Comment by bms63** [comment]
@sheramin use `devtools::install_dev_deps(dependencies = TRUE)` to get all packages from Imports and Suggests installed

**Pull request closed without merging**
