### PR TITLE
Closes #1499 remove depreciated func adsl template@devel

### LINKED ISSUE #1499: Bug: Remove deprecated function from adsl template
### What happened?

Still using fda age group function when it has been deprecated

image

### Session Information

R version 4.2.1 (2022-06-23)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Ubuntu 20.04.5 LTS

Matrix products: default
BLAS:   /usr/lib/x86_64-linux-gnu/atlas/libblas.so.3.10.3
LAPACK: /usr/lib/x86_64-linux-gnu/atlas/liblapack.so.3.10.3

locale:
 [1] LC_CTYPE=C.UTF-8       LC_NUMERIC=C           LC_TIME=C.UTF-8       
 [4] LC_COLLATE=C.UTF-8     LC_MONETARY=C.UTF-8    LC_MESSAGES=C.UTF-8   
 [7] LC_PAPER=C.UTF-8       LC_NAME=C              LC_ADDRESS=C          
[10] LC_TELEPHONE=C         LC_MEASUREMENT=C.UTF-8 LC_IDENTIFICATION=C   

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] tidylog_1.0.2      diffdf_1.0.4       stringr_1.4.1      lubridate_1.8.0   
[5] dplyr_1.0.10       admiral.test_0.3.0 admiral_0.8.2     

loaded via a namespace (and not attached):
 [1] rstudioapi_0.14  knitr_1.40       magrittr_2.0.3   hms_1.1.2        tidyselect_1.1.2
 [6] R6_2.5.1         rlang_1.0.6      fastmap_1.1.0    fansi_1.0.3      tools_4.2.1     
[11] xfun_0.33        utf8_1.2.2       cli_3.4.1        ellipsis_0.3.2   htmltools_0.5.3 
[16] yaml_2.3.5       assertthat_0.2.1 digest_0.6.29    tibble_3.1.8     lifecycle_1.0.2 
[21] crayon_1.5.1     tidyr_1.2.1      purrr_0.3.4      clisymbols_1.2.0 vctrs_0.4.1     
[26] glue_1.6.2       evaluate_0.16    admiraldev_0.1.0 rmarkdown_2.16   stringi_1.7.8   
[31] compiler_4.2.1   pillar_1.8.1     generics_0.1.3   pkgconfig_2.0.3 

### Reproducible Example

`admiral::use_ad_template("adsl")

### PR DESCRIPTION
**Pull request by DeclanHodges**
Hi all,
Here is a list of changes that have been made in order to address the linked issue:
- Removed the use of `derive_var_agegr_fda()` (deprecated function) in the adsl template and replaced with an example user defined function.
- Amended the deprecation message produced by `derive_var_agegr_fda()`.
- Updated the "Creating ADSL" vignette to reflect the changes to the adsl template.

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by DeclanHodges** [comment]
Hi all,
when running the `devtools::check()` function, I'm getting a number of errors relating to various vignettes, such as the one below:
image
It seems as though R can't find the `assert_date_vector()` function, which traces back to `compute_tmf()` within derive_date_vars.R. Does anyone know if `assert_date_vector()` is a function that used to be in `admiraldev`, but has now been removed?

**Comment by bms63** [comment]
> Hi all, When running the `devtools::check()` function, I'm getting a number of errors relating to various vignettes, such as the one below: image It seems as though R can't find the `assert_date_vector()` function, which traces back to `compute_tmf()` within derive_date_vars.R. Does anyone know if `assert_date_vector()` is a function that used to be in `admiraldev`, but has now been removed?

Try re-installing admiraldev from github.  There were some updates

**Comment by bms63** [comment]
remotes::install_github("pharmaverse/admiraldev", ref = "devel")

**Comment by DeclanHodges** [comment]
> remotes::install_github("pharmaverse/admiraldev", ref = "devel")

Ah thank you, that's solved the issue. All of the workflows are passed now, so the PR is ready for review.

**Review by bundfussr — APPROVED** [review]

**Review by bms63 — APPROVED** [review]
Looks great Declan!  Thanks for seeing this through.

**Pull request merged**
