### PR TITLE
Close #1206 Avoid error when dose_date is a renamed variable (2nd attempt)

### LINKED ISSUE #1206: Bug: Not able to rename variables with `derive_vars_last_dose()`
### What happened?

`derive_vars_last_dose()` returns an error when using the `new_vars` parameter to rename variables.

### Session Information

```
R version 3.6.3 (2020-02-29)
Platform: x86_64-pc-linux-gnu (64-bit)
Running under: Red Hat Enterprise Linux

Matrix products: default
BLAS/LAPACK: /usr/lib64/libopenblas-r0.2.20.so

locale:
 [1] LC_CTYPE=en_US.UTF-8       LC_NUMERIC=C               LC_TIME=en_US.UTF-8       
 [4] LC_COLLATE=en_US.UTF-8     LC_MONETARY=en_US.UTF-8    LC_MESSAGES=en_US.UTF-8   
 [7] LC_PAPER=en_US.UTF-8       LC_NAME=C                  LC_ADDRESS=C              
[10] LC_TELEPHONE=C             LC_MEASUREMENT=en_US.UTF-8 LC_IDENTIFICATION=C       

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] rice_2.0        lubridate_1.7.8 dplyr_1.0.0     admiral_0.7.0  

loaded via a namespace (and not attached):
 [1] Rcpp_1.0.4.6     tidyr_1.0.2      crayon_1.3.4     assertthat_0.2.1 R6_2.4.1         lifecycle_0.2.0 
 [7] magrittr_1.5     httr_1.4.1       pillar_1.4.3     stringi_1.4.6    rlang_1.0.2      cli_3.3.0       
[13] rstudioapi_0.11  vctrs_0.4.1      generics_0.0.2   ellipsis_0.3.2   tools_3.6.3      stringr_1.4.0   
[19] glue_1.6.2       purrr_0.3.4      hms_0.5.3        compiler_3.6.3   pkgconfig_2.0.3  tidyselect_1.1.0
[25] tibble_3.0.1    
```

### Reproducible Example

```r
adae <- tibble::tribble(
  ~USUBJID, ~AESTDTC, ~AENDTC, ~ASTDT, ~AENDT, ~AEDECOD,
  "P01", "2022-01-10", "2022-01-12", ymd("2022-01-10"), ymd("2022-01-12"), "Nausea",
  "P02", "2022-01-31", "2022-01-31",ymd("2022-01-31"), ymd("2022-01-31"), "Vomitting",
  "P02", "2022-02-02", "2022-02-04", ymd("2022-02-02"), ymd("2022-02-04"), "Vomitting"
)

adex <- tibble::tribble(
  ~USUBJID, ~EXTRT, ~EXDOSFRQ, ~EXSTDTC, ~EXENDTC, ~ASTDT, ~AENDT,
  "P01", "Drug A", "QD", "2022-01-09", "2022-01-12", ymd("2022-01-09"), ymd("2022-01-12"),
  "P02", "Drug A", "QD", "2022-02-01", "2022-02-04", ymd("2022-02-01"), ymd("2022-02-04")
)

(adex_single <- create_single_dose_dataset(adex))

derive_vars_last_dose(
  adae,
  adex_single,
  by_vars = vars(USUBJID),
  dose_date = EXSTDT,
  analysis_date = AESTDTC,
  new_vars = vars(EXSTDT = ASTDT)
)
```
```
Error in `assert_data_frame()`:
! Required variable `EXSTDT` is missing
Run `rlang::last_error()` to see where the error occurred.
```

### PR DESCRIPTION
**Pull request by thomas-neitmann**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Review by bms63 — COMMENTED** [review]
Can you re-label the Tests so it follow our unit test strategy 
image

**Review by bms63 — COMMENTED** [review]
Is this supposed to link to something else? 
image

**Comment by thomas-neitmann** [comment]
@bms63 Updated as requested.

**Comment by bms63** [comment]
@thomas-neitmann Got a lint issue

**Review by bms63 — APPROVED** [review]
Tests look so nice!

**Pull request merged**
