### PR TITLE
Closes #1540 tte NA bug for ADT set to NA because of missing start_date

### LINKED ISSUE #1540: Bug: `ADT` is set to `NA` when `start_date` is missing
### What happened?

When using `derive_param_tte()` the `ADT` variable is set to `NA` if `start_date` is missing for that subject even though there is an event with a valid date.

### Session Information

```
R version 4.2.1 (2022-06-23)
Platform: aarch64-apple-darwin20 (64-bit)
Running under: macOS Monterey 12.6

Matrix products: default
LAPACK: /Library/Frameworks/R.framework/Versions/4.2-arm64/Resources/lib/libRlapack.dylib

locale:
[1] en_US.UTF-8/en_US.UTF-8/en_US.UTF-8/C/en_US.UTF-8/en_US.UTF-8

attached base packages:
[1] stats     graphics  grDevices utils     datasets  methods   base     

other attached packages:
[1] admiral_0.8.3

loaded via a namespace (and not attached):
 [1] rstudioapi_0.14  magrittr_2.0.3   hms_1.1.2        tidyselect_1.2.0 R6_2.5.1         rlang_1.0.6      fansi_1.0.3      stringr_1.4.1    dplyr_1.0.10     tools_4.2.1      utf8_1.2.2       cli_3.4.1        DBI_1.1.3        withr_2.5.0     
[15] ellipsis_0.3.2   assertthat_0.2.1 tibble_3.1.8     lifecycle_1.0.3  tidyr_1.2.1      purrr_0.3.5      vctrs_0.4.1      glue_1.6.2       admiraldev_0.1.0 stringi_1.7.8    compiler_4.2.1   pillar_1.8.1     generics_0.1.3   lubridate_1.8.0 
[29] pkgconfig_2.0.3 
```

### Reproducible Example

```r
library(admiral)

adsl <- structure(list(STUDYID = structure("GSK123456", label = "Study Identifier"), 
    USUBJID = structure("GSK123456-1101", label = "Unique Subject Identifier"), 
    ARMCD = structure("P", label = "Planned Arm Code"), ACTARM = structure("Placebo", label = "Description of Actual Arm"), 
    ACTARMCD = structure("P", label = "Actual Arm Code"), TRT01P = structure("Placebo", label = "Planned Treatment"), 
    TRT01PN = structure(2, label = "Planned Treatment (N)"), 
    TRT01A = structure("Placebo", label = "Actual Treatment"), 
    TRT01AN = structure(2, label = "Actual Treatment  (N)"), 
    SAFFL = structure("Y", label = "Safety Population Flag"), 
    MITTFL = structure("Y", label = "Modified Intent-to-Treat Population Flag"), 
    RANDFL = structure("Y", label = "Randomized Population Flag"), 
    TRTSDT = structure(NA_real_, label = "Date of First Exposure to Treatment", format.sas = "DATE", class = "Date"), 
    TRTEDT = structure(NA_real_, label = "Date of Last Exposure to Treatment", format.sas = "DATE", class = "Date"), 
    LSTALVDT = structure(18594, label = "Last Date Known Alive", format.sas = "DATE", class = "Date")), class = c("tbl_df", 
"tbl", "data.frame"), row.names = c(NA, -1L), label = "character(0)")

adae <- structure(list(STUDYID = structure("GSK123456", label = "Study Identifier"), 
    USUBJID = structure("GSK123456-1101", label = "Unique Subject Identifier"), 
    AGE = structure(62, label = "Age"), AGEGR1 = structure("<65", label = "Pooled Age Group 1"), 
    ACOUNTRY = structure("Canada", label = "Analysis Country"), 
    SEX = structure("F", label = "Sex"), RACE = structure("MULTIPLE", label = "Race"), 
    TRT01P = structure("Placebo", label = "Planned Treatment"), 
    TRT01PN = structure(2, label = "Planned Treatment (N)"), 
    TRT01A = structure("Placebo", label = "Actual Treatment"), 
    TRT01AN = structure(2, label = "Actual Treatment  (N)"), 
    AESTDTC = structure("2020-09-10", label = "Start Date/Time of Adverse Event"), 
    AESEQ = structure(1, label = "Adverse Event Sequence"), AEENDTC = structure("2020-10-04", label = "End Date/Time of Adverse Event"), 
    ASTDT = structure(18515, label = "Analysis Start Date", format.sas = "DATE", class = "Date"), 
    AENDT = structure(18539, label = "Analysis End Date", format.sas = "DATE", class = "Date"), 
    AEBODSYS = structure("CARDIAC DISORDERS", label = "Body System or Organ Class"), 
    AETERM = structure("VENTRICULAR HYPERTROPHY", label = "Reported Term for the Adverse Event"), 
    AEDECOD = structure("VENTRICULAR HYPERTROPHY", label = "Coded Term for the Adverse Event"), 
    AESPROT = structure("N", label = "Protocol Specificed Event"), 
    AESEV = structure("MILD", label = "Adverse Event Severity"), 
    AEOUT = structure("RECOVERED/RESOLVED", label = "Adverse Event Outcome")), class = c("tbl_df", 
"tbl", "data.frame"), row.names = c(NA, -1L), label = "character(0)")

lstalv_censor <- censor_source(
  "adsl",
  date = LSTALVDT,
  set_values_to = vars(
    EVNTDESC = "Last Known Alive Date",
    SRCDOM = "ADSL",
    SRCVAR = "LSTALVDT"
  )
)

any_ae_src <- event_source(
  dataset_name = "adae",
  date = ASTDT,
  set_values_to = vars(
    EVNTDESC = "Any Adverse Event",
    SRCDOM = "ADAE",
    SRCVAR = "AEDECOD",
    SRCSEQ = AESEQ
  )
)

adaette_any_ae <- derive_param_tte(
  dataset_adsl = adsl,
  source_datasets = list(adae = adae, adsl = adsl),
  start_date = TRTSDT,
  event_conditions = list(any_ae_src),
  censor_conditions = list(lstalv_censor),
  set_values_to = vars(
    PARAMCD = "ANYAETTE",
    PARAM = "Time to any first adverse event"
  )
)

print(adaette_any_ae)
```

```
# A tibble: 1 × 11
  STUDYID   USUBJID        EVNTDESC          SRCDOM SRCVAR  SRCSEQ  CNSR ADT    STARTDT PARAMCD  PARAM                          
  <chr>     <chr>          <chr>             <chr>  <chr>    <dbl> <int> <date> <date>  <chr>    <chr>                          
1 GSK123456 GSK123456-1101 Any Adverse Event ADAE   AEDECOD      1     0 NA     NA      ANYAETTE Time to any first adverse event
```

### PR DESCRIPTION
**Pull request by jcabercrombie**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by jcabercrombie** [comment]
Hi @thomas-neitmann ! I have all but one checkbox completed for the merge request. When reviewing to resolve the merge conflict, I noticed there are already new tests present in the test-derive_param_tte.R that make mine seem to technically be Test #12. Even when moving my test to the bottom and renumbering it to #12, the merge conflict persists. Any advice so I can fix this quickly for review to happen?

**Comment by thomas-neitmann** [comment]
Thanks a lot @jcabercrombie! I went ahead and fixed the merge conflict. That's a very mean for for a 1st PR.

**Review by thomas-neitmann — CHANGES_REQUESTED** [review]
Just one minor comment.

In addition please rename the branch by including the `@devel` suffix in the name. This will ensure that the upstream dependencies {ådmiral.test} and {admiraldev} are installed from the `devel` rather than the `main` branch in the `R CMD check` workflow. The reason why this workflow currently fails is because we're using features from the `devel` branch of these packages.

To rename the branch please run the following commands in the RStudio terminal:

```
git checkout 1540_tte_na_bug
git pull
git branch -M 1540_tte_na_bug@devel
git push -u origin 1540_tte_na_bug@devel
```

Then open a *new* pull request for this renames branch. Thanks!

**Comment by bms63** [comment]
Hi - can we close this PR?

**Comment by jcabercrombie** [comment]
Yes, this can be closed/gotten rid of! I created another PR with the correct branch suffix that Thomas requested.

**Pull request closed without merging**
