### PR TITLE
Release v0.7.0

### PR DESCRIPTION
**Pull request by bms63**
# Release Description

Release of 0.7.0 admiral 

# Release Checklist

- [x] Version number has been updated
- [x] Description file updated with New Developers (if applicable)
- [x] NEWS.md: Double check formatting, placement of items, issues linked appropriately
- [ ] NEWS.md: Deprecated from previous release have been removed - verify
- [ ] Ensure Test Coverage Badge is Green and on Readme
- [ ] Ensure CMD Checks are passing and says Passing Badge on Readme
- [ ] GitHub actions on this PR are all passing
- [ ] First release to CRAN - `devtools::build()` and work through prompts
- [ ] Incorporate feedback from CRAN and then do a GitHub release (minimizes needed to do mini-releases)
- [ ] Website is deployed and visual checks for integrity completed
- [ ] Prepare and Post announcements for Linked-In and Slack Channels for Release

# Clean up Checklist

- [ ] Delete branches that are stale or abandoned or leftover from a Pull Request
- [ ] Triage and close issues that were not closed properly via PRs that made it into release 
- [ ] Close Pull Requests that are stale 
- [ ] Set up and increment News/Changelog Skeleton
- [ ] Retire labels specific to a time-period (testing feedback) if no longer in use
- [ ] Remove Users with no activity for 12 months from Repository

### CODE REVIEW

**Comment by thomas-neitmann** [comment]
@dinakar29 Can you take a look at the failing "Man Pages" workflow. Not sure what's wrong there...

**Comment by dinakar29** [comment]
> @dinakar29 Can you take a look at the failing "Man Pages" workflow. Not sure what's wrong there...

Taking a look now

**Comment by dinakar29** [comment]
Ah it's a bug in the workflow. Fix incoming in a separate PR.

**Comment by bms63** [comment]
> Ah it's a bug in the workflow. Fix incoming in a separate PR.

@dinakar29  Do you know how to fix our code coverage and rmd check badges?  I've been messing around with it a bit to no avail.  

I can review PR once you have it ready.

**Comment by dinakar29** [comment]
I actually will not be able to fix your CodeCoverage badge as your repo is using a third party service (https://app.codecov.io/gh/pharmaverse/admiral?branch=devel) for code coverage. 

I can fix the R CMD check badge, though, since it's GH actions.

**Comment by bms63** [comment]
> I actually will not be able to fix your CodeCoverage badge as your repo is using a third party service (https://app.codecov.io/gh/pharmaverse/admiral?branch=devel) for code coverage.
> 

yeah it seems we need admins to of the pharmaverse ogranization to make this happen @pharmaverse/core-team 

> I can fix the R CMD check badge, though, since it's GH actions.

please and thank you.

**Comment by dinakar29** [comment]
Here ya go: https://github.com/pharmaverse/admiral/pull/1161

**Comment by rossfarrugia** [comment]
@bms63 @dinakar29 i accepted the "Request to install Codecov in pharmaverse" email and chose admiral and admiralonco repos. let me know if anything else needed from a pharmaverse org admin for this.

**Comment by dinakar29** [comment]
> @bms63 @dinakar29 i accepted the "Request to install Codecov in pharmaverse" email and chose admiral and admiralonco repos. let me know if anything else needed from a pharmaverse org admin for this.

@rossfarrugia - it looks like the Codecov report was published to `Roche-GSK/admiral`. I believe some additional settings need to change on the codecov side.

Also, I'd be wary of using codecov given they've been breached via a [massive supply chain attack](https://about.codecov.io/security-update/) which affected a large number of OSS projects recently. My recommendation is that you do not use their services, but totally up to you if you accept the risks and prefer it over something else.

**Comment by rossfarrugia** [comment]
thanks @dinakar29 for the advice! i've revoked access for now then and will wait for @bms63 & @thomas-neitmann to comment. maybe we can leave out of this release and make a call on future strategy after if possible?

**Comment by bms63** [comment]
> thanks @dinakar29 for the advice! i've revoked access for now then and will wait for @bms63 & @thomas-neitmann to comment. maybe we can leave out of this release and make a call on future strategy after if possible?

Is there an alternative service to use for codecov?  We have it set up for metatools, so if we don't want to use it for admiral and admiralonco for the attack issues, then maybe we need to remove it off metatools?

Looking over this report - https://blog.gitguardian.com/codecov-supply-chain-breach/  It seems they were trying to get tokens and secret keys  in private git repos using codecov as a way to get into them.  Do you think this is an issue for us?  I look into it a bit more, but I feel like this is a big issue for us.  @thomas-neitmann

**Review by bundfussr — APPROVED** [review]

**Review by thomas-neitmann — APPROVED** [review]

**Pull request merged**
