### PR TITLE
Closes #1839 dummy function created

### PR DESCRIPTION
**Pull request by sheramin**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF version of it to the same folder.
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by sheramin** [comment]
@bms63 Thank you for reviewing it. I couldn't pass one of those checks (item h), which is running the `pkgdown::build_site()`. It seems there's a problem in one of the functions (please let me know if I need to post the function and file name). The CMD check passed too, but that one, nope! I'm attaching a snippet of that error:
image

**Comment by bms63** [comment]
> @bms63 Thank you for reviewing it. I couldn't pass one of those checks (item h), which is running the `pkgdown::build_site()`. It seems there's a problem in one of the functions (please let me know if I need to post the function and file name). The CMD check passed too, but that one, nope! I'm attaching a snippet of that error: image

Interesting - what version of `admiral` do you have installed?

**Comment by sheramin** [comment]
> > @bms63 Thank you for reviewing it. I couldn't pass one of those checks (item h), which is running the `pkgdown::build_site()`. It seems there's a problem in one of the functions (please let me know if I need to post the function and file name). The CMD check passed too, but that one, nope! I'm attaching a snippet of that error: image
> 
> Interesting - what version of `admiral` do you have installed?

It's 1.0.1:
image

**Comment by bms63** [comment]
So that argument was deprecated and I can see the function using `set_values_to` in the main branch

image

Can you try restarting the session and re-installing the package.  Something fishy is going on!!  It is something just not synching up correctly!  :)

**Comment by sheramin** [comment]
> So that argument was deprecated, `analysis_var`, and I can see the function using `set_values_to` in the main branch
> 
> image
> 
> Can you try restarting the session and re-installing the package. Something fishy is going on!! It is something just not synching up correctly! :)

I tried re-installing the package, duplicated the branch and restarting the session multiple times - I still get that error.

**Comment by bms63** [comment]
@pharmaverse/admiral what are we missing?

@sheramin Can you verify that the code isn't there for analysis_var?

Also can you check your package panes to see if there are not multiple copies of admiral available?  possible have it stored in another directory that pkgdown is pulling from??

**Comment by sheramin** [comment]
> you verify that the code isn't there fo



> @pharmaverse/admiral what are we missing?
> 
> @sheramin Can you verify that the code isn't there for analysis_var?
> 
> Also can you check your package panes to see if there are not multiple copies of admiral available? possible have it stored in another directory that pkgdown is pulling from??

Sure, I do not see `analysis_var` in the .Rmd file:
image

But I see that variable in the .R file, although I'm not quite sure if that function gets called from `derive_param_exposure.R`
image

It doesn't look like there are multiple copies of `admiral`. Just making sure I'm following where to look, here is a screenshot:
image

**Comment by manciniedoardo** [comment]
@sheramin when you run `devtools::document()` does the .Rmd file update?

**Comment by sheramin** [comment]
> @sheramin when you run `devtools::document()` does the .Rmd file update?

which .Rmd file? If you meant `bds_exposure.Rmd`, no it doesn't update that I believe (I checked the last modified date after running `devtools::document`. But, it does update some other files like NAMESPACE. I also updated the NEWS.md manually.

Here is what I get when run `devtools::document()`
image

**Comment by manciniedoardo** [comment]
@sheramin my thinking was that running `devtools::document()` should regenerate the .Rmd documentation files, so for `derive_param_exposure()`, if your .R file was showing the newest version of the function then the .Rmd should update to show that too.

**Comment by sheramin** [comment]
Thank you all! With Zelos (@zdz2101)'s help the issue resolved.

**Comment by zdz2101** [comment]
Excellent job @sheramin , we will close, feel free to pick up issues as soon as you're comfortable to do so!

**Pull request closed without merging**
