### PR TITLE
#968 - changed all reference from admiral.xxx to admiraxxx

### PR DESCRIPTION
**Pull request by ClaudiaCarlucci**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Comment by ClaudiaCarlucci** [comment]
@rossfarrugia I got issues when I run R CMD check as it doesn't find "admiraltest" package and it failed on creating vignettes

**Comment by bms63** [comment]
We need to update admrial.test to admrialtest for this to work.  I think this will need to be done right before the release and take some coordination between the two packages.

**Comment by rossfarrugia** [comment]
agree @bms63 see https://github.com/pharmaverse/admiral.test/pull/26 - will also need updating on CRAN to replace admiral.test FYI @thomas-neitmann

**Comment by rossfarrugia** [comment]
@bms63 i added you as a reviewer here. all looks fine to me, but this way you can approve and merge at the time you think best, so that it doesn't cause any issues to others working on latest devel version pre-release. for the admiraltest PR mentioned above i'll merge that into devel for now, and then we'd just need to merge into main and rename the github folder from admiral.test->admiraltest. let me know the timing you want to go for here. the only consideration i had is that given this PR changes so many files, we may get a bunch of merge conflicts if we leave it right until end of April to merge.

**Comment by bms63** [comment]
@bundfussr and @statasaurus  we should be ready to dance!!  changing package names...what could go wrong!

**Comment by rossfarrugia** [comment]
good spot @bms63!

@ClaudiaCarlucci can you update for this please at admiral/.github/workflows/R-CMD-check.yml

**Comment by bms63** [comment]
It looks like this got updated already

**Comment by bms63** [comment]
but maybe i should do in seperate branch and then you all can pull down ??

**Comment by ClaudiaCarlucci** [comment]
I tried to commit again but I still got the same issues (there is no package called 'admiraltest').  Can you please let me know if I'm missing any step? Thanks.

**Comment by bms63** [comment]
It seems to be working after I toyed around with it.  Takes forever to run the 3.6 check...

Not sure of the slowness.  

We can merge into `devel `and then I can merge into one of my branches and take it for a spin.

**Review by rossfarrugia — APPROVED** [review]
Approving to try and kick off the final couple of automated checks

**Comment by rossfarrugia** [comment]
@bms63 @thomas-neitmann i'm going to merge this as i believe the check templates error is to be expected until we get admiraltest to CRAN: 
Error: Error in library(admiraltest) : there is no package called ‘admiraltest’

**Comment by rossfarrugia** [comment]
Thanks @ClaudiaCarlucci for all your efforts!

**Pull request merged**
