### PR TITLE
Closes #1434 fix badges

### LINKED ISSUE #1434: General Issue: Badges need to be updated with replacement badges for admiralci workflows
### Background Information

Badges need to be updated with replacement badges for admiralci workflows

### Definition of Done

Badges updated

### PR DESCRIPTION
**Pull request by bms63**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/main/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/main/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/main/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by bms63** [comment]
I got rid of some of the badges - and renamed to admiral workflows.  What do we think?

image

**Comment by bundfussr** [comment]
I think "Admiral workflows" is too unspecific. Most users do not know the admiral workflows.

**Comment by bms63** [comment]
What about  `admiral CI/CD workflows`.  I think most people that CI/CD is some fancy software stuff that is important even if they can't really put their finger on it

**Comment by cicdguy** [comment]
> 

Yes, renaming is possible directly in this line: https://github.com/pharmaverse/admiral/blob/main/.github/workflows/common.yml#L5

**Comment by bundfussr** [comment]
As we can not use a label (like R-CMD or lintr) which is familiar to most R users, I would remove the badge. However, let's discuss tomorrow and see what the others think.

**Comment by bms63** [comment]
Hey all,

We never reached a decision on what to call the workflow.  I decided upon `admiral CI/CD Workflows`.  I changed the hyerlink so if someone clicks on the badge to find out what the workflows are it takes them to here 
image

**Comment by cicdguy** [comment]
> Hey all,
> 
> 
> 
> We never reached a decision on what to call the workflow.  I decided upon `admiral CI/CD Workflows`.  I changed the hyerlink so if someone clicks on the badge to find out what the workflows are it takes them to here 
> 
> image
> 
> 

That's actually brilliant.

**Comment by bms63** [comment]
@bundfussr @thomas-neitmann What do you all think?  We could come up with a better solution later.  I just like the readme to not look like this anymore 
image

**Comment by bundfussr** [comment]
I still think that the badge does not add value for the users (even with the link). The admiralci page describes the workflows provided by admiralci but not those which were actually used by the package which has the badge. It also does not provide information about which workflows passed and which failed.

@pharmaverse/admiral , what do you think?

**Comment by bms63** [comment]
I think we could update the admiralci page to be more informative of which actions are being used in what repos down the road.  I can't imagine many users are going to go too deep into looking at our CI/CD workflows.  

Honestly, I think the badge it is kind of a cool thing to have linked onto repo that showcases all the fancy CI/CD stuff we do for this package.  However, if no one else responds, then I will just remove it.  It seems like @cicdguy likes it, but he is a little biased! :)  

Should we remove test coverage badge as well?  We don't explain what 97% really means anywhere and the links just goes to an empty actions page - so not very informative to the users.

**Comment by bundfussr** [comment]
I would keep the test coverage badge because many R users know `devtools::test_coverage()` and the test coverage badge is used by many other projects. So the meaning should be clear for most of the users.

**Comment by bms63** [comment]
I removed the CI/CD badge.  All good @bundfussr ?

**Review by bundfussr — APPROVED** [review]

**Pull request merged**
