### PR TITLE
 Closes #693 join documentation

### LINKED ISSUE #693: Join documentation of `*_source()` and accompanying derivation
`dthcaus_source()` and `derive_var_dthcaus()` as well as `lstalvdt_source()` and `derive_var_lstalvt()` should be described on the same help page as these functions can only be used in conjunction.

### PR DESCRIPTION
**Pull request by w316liu**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #693  into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Review by thomas-neitmann — APPROVED** [review]
You'll have to run `devtools::document()` once and commited all updated files. Otherwise merging is blocked due to the failing "Man Pages" workflow.

**Comment by w316liu** [comment]
@thomas-neitmann in the _Man Pages_ check, it installed roxgen 7.2.1. However, in the devel/DESCRIPTION, the roxgen version is 7.2.0, it the check failed. I'm hesitant to modify the DESCRIPTION file to change the version. Any suggestion?

**Comment by cicdguy** [comment]
Yeah, admiral does not use the common workflows from admiralci: https://github.com/pharmaverse/admiral/pull/1287
I'll update this for admiral.

**Comment by bms63** [comment]
@w316liu Do you have time to fix this man failing action?  We are trying to get all these PRs wrapped up by Monday.

**Comment by w316liu** [comment]
@thomas-neitmann @cicdguy Any guidance on resolving the Man failing issue?

**Comment by bms63** [comment]
@w316liu you should be able to just `roxygen2::roxygenize('.', roclets = c('rd', 'collate', 'namespace'))` in the console and push up any changes.  This should resolve it.

**Comment by w316liu** [comment]
@bms63 Nothing changed in local after running the suggested code. What else can I try?

**Comment by cicdguy** [comment]
I think @thomas-neitmann had mentioned this to me - since the Roxygen workflow isn't the same as that in admiralci (i.e not the same as the one in the renv.lock), there could be a discrepancy. It's okay if this fails, I'll fix it separately.

**Comment by cicdguy** [comment]
> > roxygen2
> 
> 
> 
> ok, the DESCRIPTION lists roxygen2 7.2.0. I locally uses 7.2.0 as well. But the check is 7.2.1
> 
> 
> 
> other attached packages:
> 
> [1] roxygen2_7.2.0     admiral_0.8.0      stringr_1.4.0      lubridate_1.7.4    dplyr_0.8.5       
> 
> [6] admiral.test_0.2.0

Right, exactly. The workflow is broken and needs fixing. Hence, please ignore it for now. I'll fix it separately.

**Comment by bms63** [comment]
I'm sort of uncertain of what is going on here.  As we several other PRs using the same action that are not failing.

**Review by bundfussr — CHANGES_REQUESTED** [review]
I think we should not use `@describeIn` because `derive_var_dthcaus()` and `dthcaus_source()` have completely different arguments and return values. Thus putting the arguments and return values of both functions in the same section makes the documentation hard to read.
I would describe the functions on the same page only if we can have separate sections for each. Unfortunately, I have no idea how to achieve this.

@thomas-neitmann , @bms63 , what do you think?

**Comment by cicdguy** [comment]
@w316liu and @bms63 - @thomas-neitmann has merged in the updated workflows to `devel`. Merging `devel` into this branch should take care of all workflow discrepancies.

**Comment by w316liu** [comment]
@cicdguy I've fixed the spelling error by adding the words to the inst/WORDLIST and pushed the change.
Can you rerun the check?

**Comment by thomas-neitmann** [comment]
@w316liu It's already running automatically 🙂

**Comment by w316liu** [comment]
> I think we should not use `@describeIn` because `derive_var_dthcaus()` and `dthcaus_source()` have completely different arguments and return values. Thus putting the arguments and return values of both functions in the same section makes the documentation hard to read. I would describe the functions on the same page only if we can have separate sections for each. Unfortunately, I have no idea how to achieve this.
> 
> @thomas-neitmann , @bms63 , what do you think?

do we wanna deal with this change in this release?

**Comment by bms63** [comment]
Can we just to a specific call with @seealso [dthcaus_source()] to link that documentation together?  It is confusing having them laid out in the usage section like this 

image

**Comment by w316liu** [comment]
@Seealso is already in current version. If we decided not to join the documentation using @Describein, we just DO NOT MERGE this branch. @thomas-neitmann how do you think?

**Comment by thomas-neitmann** [comment]
Even though joining the documentation pages does have the drawbacks outlined by @bundfussr I still feel it's much easier seeing these two functions which are meant to be used together on a single help page. Thus, my suggestion is to go ahead and merge this PR.

**Comment by bms63** [comment]
Is @rdname an option here ? https://stackoverflow.com/questions/57390342/use-roxygen2-to-document-multiple-datasets-in-a-single-documentation-object

**Comment by w316liu** [comment]
For this issue specifically, @rdname will result in the same documentation format.

**Comment by bms63** [comment]
Well then...I got nothing.  Just fix the merge conflict and then we can merge in.

**Comment by bms63** [comment]
@bundfussr can you approve.  ty

**Comment by w316liu** [comment]
one more check fails. Not sure why it popped out.

### Errors in README.md
* [https://www.r-pkg.org/badges/version/admiral](https://www.r-pkg.org/badges/version/admiral): Failed: Network error (status code: 404)

**Comment by bms63** [comment]
> one more check fails. Not sure why it popped out.
> 
> ### Errors in README.md
> * https://www.r-pkg.org/badges/version/admiral: Failed: Network error (status code: 404)

That website is down - I think we can safely ignore.

**Comment by bundfussr** [comment]
If we go ahead with this approach, we should at least be consistent and update `derive_var_extreme_dt()`, `derive_var_extreme_dtm()`, `derive_param_tte()`, and `create_query_data()` as well.

**Pull request merged**
