### PR TITLE
666 - added FAQ for testing

### PR DESCRIPTION
**Pull request by rossfarrugia**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://roche-gsk.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [X ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [X ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://roche-gsk.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [X ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://roche-gsk.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [X ] Update to all relevant roxygen headers and examples 
- [X ] Run `devtools::documents()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [X ] Address any updates needed for vignettes and/or templates
- [X ] Update `NEWS.md`
- [X ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://roche-gsk.github.io/admiral/reference/index.html)" page. 
- [X ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [X ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [X ] Link the issue so that it closes after successful merging. 
- [X ] Address all merge conflicts and resolve appropriately 
- [X ] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Comment by rossfarrugia** [comment]
@koegerr i added the one extra FAQ question and also removed some blank lines.

**Comment by rossfarrugia** [comment]
@thomas-neitmann i got some fails for "R-CMD-check / ubuntu-20.04 (release)" but can't see why from the messages and the minor updates I made. has this happened for any other recent PRs?

**Comment by thomas-neitmann** [comment]
This is not related to any changed you've made. We fixed the failing test cases on the `devel` branch. To get those changes into your branch please run the following commands in your RStudio **terminal**:

```
git checkout devel
git pull
git checkout 666_testing_faq
git merge --no-edit devel
git push
```

**Comment by rossfarrugia** [comment]
Thanks @thomas-neitmann - that fixed it! appreciate if you or @koegerr could review and merge this PR.

**Review by thomas-neitmann — APPROVED** [review]

**Pull request merged**
