### PR TITLE
Remove {admiraldev} and {admiral.test} from lock file

### PR DESCRIPTION
**Pull request by thomas-neitmann**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [ ] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [ ] Update to all relevant roxygen headers and examples 
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately 
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by bms63** [comment]
STill not entirely clear what is going on here.  Is `admiraldev` not being installed separately.  The snapshot doesn't have `admiraldev` which is why I think this is failing??

**Comment by thomas-neitmann** [comment]
Super strange. I cannot reproduce this locally. Any ideas @cicdguy?

**Comment by cicdguy** [comment]
Is `admiral.test` compatible with R 3.6?
Workflows there suggest that no testing was done with R 3.6: https://github.com/pharmaverse/admiral.test/tree/devel/.github/workflows

The bigger question is - if you're releasing to CRAN _now_ (when CRAN runs on R 4.2.1), why even bother running checks on R 3.6.3 and having an extremely outdated renv.lock file? Shouldn't you keep this current?

**Comment by bms63** [comment]
> 

People still use version 3.6 in certain companies, but that is dwindling,   I think we should always test the oldest version and develop in the oldest version as well to head off any nasty surprises

**Comment by cicdguy** [comment]
> People still use version 3.6 in certain companies, but that is dwindling,   I think we should always test the oldest version and develop in the oldest version as well to head off any nasty surprises

That's an interesting approach.

Typically when you write software, you develop against the latest versions of things and perform regression testing against older dependencies and runtimes to make sure the changes are backwards compatible. This way your software benefits from the latest features, performance updates, bugfixes, security updates etc.

Finally, prior to making a release, one would lock those versions of dependencies to a specific version for reproducibility purposes.

**Comment by bms63** [comment]
> > People still use version 3.6 in certain companies, but that is dwindling,   I think we should always test the oldest version and develop in the oldest version as well to head off any nasty surprises
> 
> That's an interesting approach.
> 
> Typically when you write software, you develop against the latest versions of things and perform regression testing against older dependencies and runtimes to make sure the changes are backwards compatible. This way your software benefits from the latest features, performance updates, bugfixes, security updates etc.
> 
> Finally, prior to making a release, one would lock those versions of dependencies to a specific version for reproducibility purposes

Well, we could move to developing in the latest version and then test that it still works back to 3.6.  I always thought it was easier to start in the oldest version and go forward.  But this is my first big software dev project - so all this stuff is new to me!!  @thomas-neitmann @bundfussr

**Comment by cicdguy** [comment]
I believe it would be a significant paradigm shift to change the process at this stage in the project, so I'd say sticking to the original process is okay. 

We can discuss this separately when we meet next.

As for the 3.6 man pages workflow failing, I believe there's some funkiness associated with admiraldev and admiral.test and their compatibility with R 3.6 (likely due to a dependency somewhere).

**Comment by bms63** [comment]
@thomas-neitmann Shall we close this PR - I think the coming repropagation form admiralci addresses this

**Comment by thomas-neitmann** [comment]
Fine with me.

**Pull request closed without merging**
