### PR TITLE
Add ability to preview docs on PR to devel

### PR DESCRIPTION
**Pull request by dinakar29**
This will help spot weird formatting issues that tend to creep in over time.

### CODE REVIEW

**Comment by dinakar29** [comment]
Note that the `pkgdown` workflow takes 15+ minutes per run. This will be costly to DX and productivity, and of course compute resources. I'd advise against this, but it's up to you, @bms63 & @thomas-neitmann.

**Comment by dinakar29** [comment]
Artifact resulting from this run can be found here: https://github.com/pharmaverse/admiral/actions/runs/2450586082
Needs to be downloaded and rendered locally.

**Comment by thomas-neitmann** [comment]
> Note that the `pkgdown` workflow takes 15+ minutes per run. This will be costly to DX and productivity, and of course compute resources. I'd advise against this, but it's up to you, @bms63 & @thomas-neitmann.

How about going forward we have a `pre-release` branch which we use for the final adjustment prior to a new release? Then we could trigger this workflow only on changes to `pre-release`.

**Comment by bms63** [comment]
`pre-release` branch makes more sense to me to save resources and take in your advice @dinakar29 .  Also will help with timing  of release of the website with the actual release to CRAN.

We also ask our developers to build the pkgdown site as part of the pull request checklist, but I've found some people don't really follow through with this task.  :(  When enough people forgo this item it just cascades issues into our website.

**Comment by dinakar29** [comment]
@thomas-neitmann So if we do create a pre-release branch - what does final release management strategy look like?

Something like this?

```mermaid
graph TD
  devel --> pre-release
  pre-release --> main
  main --> tag/release
```

**Comment by dinakar29** [comment]
Hi @bms63 - there is a way to do that, but I don't have access to that S3 bucket or any other hosting service, so we're limited by GH pages for now.

**Comment by thomas-neitmann** [comment]
> @thomas-neitmann So if we do create a pre-release branch - what does final release management strategy look like?
> 
> Something like this?

That's exactly what I had in mind.

**Comment by thomas-neitmann** [comment]
> Hi @bms63 - there is a way to do that, but I don't have access to that S3 bucket or any other hosting service, so we're limited by GH pages for now.

@epijim Can we get access to that S3 bucket?

**Comment by bms63** [comment]
@epijim Any chance we can get access to the S3 bucket to host a private preview version of our website before it goes live?

**Comment by dinakar29** [comment]
All - barring the S3 bucket, I can think of another way to host the devel and pre-release version of the docs on gh-pages without any additional infrastructure needs. Watch this space for updates. Coming soon.

**Comment by thomas-neitmann** [comment]
Looking forward to your updates @dinakar29!

**Comment by dinakar29** [comment]
Closing in favor of https://github.com/pharmaverse/admiral/pull/1245

**Pull request closed without merging**
