### PR TITLE
add vbump job

### PR DESCRIPTION
**Pull request by dgrassellyb**
Closes [#admiralci/](https://github.com/pharmaverse/admiralci/issues/157)
Closes [#admiralci/](https://github.com/pharmaverse/admiralci/issues/155)

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [ ] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [ ] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [ ] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [ ] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
- [ ] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [ ] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [ ] Address any updates needed for vignettes and/or templates
- [ ] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [ ] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page. 
- [ ] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [ ] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [ ] Link the issue in the Development Section on the right hand side.
- [ ] Address all merge conflicts and resolve appropriately
- [ ] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by dgrassellyb** [comment]
Hey @cicdguy just created this one, just tricky to test without affecting main branch directly (I guess we don't want that 🙅 ) (or I would need just to make a temp branch on `insightsengineering/r.pkg.template/.github/workflows/version-bump.yaml` to be able to test the vbump but not on main branch) .. 
Also I was thinking something, maybe we should trigger this vbump only on specific changes ? for example if we push new changes on codespaces/workflows, we don't want to update the version right ? (asking @ddsjoberg as well :) )

**Comment by bundfussr** [comment]
Does the version bump workflow increase the development version only or also the patch, minor, or major version?
Does it work on the `main` branch only or also on the `patch` branch?

**Comment by bms63** [comment]
image

What a time to be alive!!

**Comment by dgrassellyb** [comment]
> Does the version bump workflow increase the development version only or also the patch, minor, or major version? Does it work on the `main` branch only or also on the `patch` branch?

It's increasing the dev version only, for more details, it's using this R function with `dev` parameter : 

Screenshot 2023-11-08 at 15 21 46

I am not sure we want to automate vbump for official release on major/minor/patch version ? (but let me know !)

**Comment by bundfussr** [comment]
> It's increasing the dev version only

Why do we want to increase the development version?

**Comment by ddsjoberg** [comment]
> Why do we want to increase the development version?

admiral has a number of reverse dependencies. if we make a change that requires an update in downstream packages, the version number is the way to determine devs of the downstream packages have the required version of admiral installed

**Comment by ddsjoberg** [comment]
@bundfussr if a user reports a bug while using version 9001 that was corrected in 9002, and we're currently on 9021, how would we know they are using a version pre or post bug fix?

Regardless, do you have an objection to including this?

**Comment by bundfussr** [comment]
> Regardless, do you have an objection to including this?

I would like to keep it as simple as possible. At the moment I see no need for increasing the development version. We need the development version only for distinguishing released versions and development versions.

I would not spend time on investigating bugs which occur in a past development version but not in the latest one.

Regarding dependencies, I think on the development version users/developers/workflows should use the latest version of the upstream dependencies. To be more precise:
- The latest released version of the upstream dependencies should be used for pull request into `patch` and for pull request into `main` where the version in the DESCIRPTION is not a development version.
- For all other pull request the `main` version of the upstream dependencies should be used.

Are the workflows implemented this way or could they be implemented this way?

**Comment by ddsjoberg** [comment]
There seems to be some disagreement on the value of adding vbump. Since the overhead here is minimal, I suggest it is added.

**Comment by dgrassellyb** [comment]
@cicdguy : working fine on my forked repo, we can merge it ! 
Screenshot 2023-11-13 at 16 40 27

Screenshot 2023-11-13 at 16 40 39

**Pull request merged**
