### PR TITLE
Closes #1989 Link Fix in `README.md`

### LINKED ISSUE #1989: Documentation:  Fix admiralonco link in Readme, add admiralvaccine
### Please select a category the issue is focused on?

_No response_

### Let us know where something needs a refresh or put your idea here!

The admiralonco link is not enabled, but the admiralophtha is for the `README.md` file.  Unsure why it is broken.

image

image

Also admiralvaccines has been deployed to CRAN and has an active website - I believe we should add this to the readme as well.

## Definition of Done

- [ ] Figure out reason for failing link for admiralonco and fix
- [ ] Add admiralvaccines to the list - https://pharmaverse.github.io/admiralvaccine/main/

### PR DESCRIPTION
**Pull request by ddsjoberg**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiraldev/devel/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #1989 into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
    - Not applicable 
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/devel/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
    - Not applicable
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#deprecation)?
    - Not applicable
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/devel/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
    - Not applicable
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
    - Not applicable
- [x] Address any updates needed for vignettes and/or templates
    - Not applicable
- [ ] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
    - I didn't update this, and I don't think it's needed. But if anyone feels differently, I can add one.
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/cran-release/reference/index.html)" page. 
    - Not applicable
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
    - Not applicable
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
    - Not sure what this means
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

Trying my first PR 😝 
- Added admiralvaccine links
- Updated links to consistently place the link, and to keep package names in curly brackets. Previously, linked packages didn't have curly brackets, and packages without a hyperlink had curly brackets. 
- I ran the spell checker to add the new admiral package names. I still have questions about what's going on with the spell checks in the repo...

### CODE REVIEW

**Comment by bms63** [comment]
pkgdown turns the ``{pkg_name}`` into hyperlinks.  This is how it is handled throughout the documentation - not sure if we want to make an exception for the readme but it is nice to have them linked on the github readme page now.

For some reason admiralonco was not making a hyperlink with ``{pkg_name}``.

If we do manually hyperlink them on the readme, then we should probably use `cran-release` rather than `main`

**Comment by ddsjoberg** [comment]
I couldn't identify a reason why the package name were auto-linking. FYI

**Comment by ddsjoberg** [comment]
Hi @bms63, I updated the admiral links to point to "cran-release", thanks

**Comment by bms63** [comment]
image

You linked the issue in the Development Section.   - [ ] 

for news, it really is a judgement call.  it doesn't really impact users so I think not mentioning helps to keep the news de-cluttered.

**Comment by bms63** [comment]
oh can you add those words to the wordlist so the spelling check passes?

**Comment by ddsjoberg** [comment]
> oh can you add those words to the wordlist so the spelling check passes?

@bms63 can we chat about this? I ran the spellchecker and it updated the WORDLIST. But the Spelling workflow is still a bit mysterious to me....

**Pull request merged**
