### PR TITLE
Closes #1204 minimum package versions@devel

### LINKED ISSUE #1204: Add minimum required version of dependency packages to DESCRIPTION file
### Background Information

Currently there is no minimum required version for {admiral.test} indicated in our DESCRIPTION file. However, the latest release only works with version 0.2.0 of {admiral.test}. If you already have {admiral.test} installed and install the latest version of {admiral} then {admiral.test} won't get updated automatically. This will lead to errors when running examples.

I think this might actually warrant a patch release, i.e. v0.7.1 of {admiral}. What do you think @pharmaverse/admiral?

### Definition of Done

DESCRIPTION fiel contains `admiral.test (>= 0.2.0)` line.

### PR DESCRIPTION
**Pull request by esimms999-gsk**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Place Closes #<insert_issue_number> into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers)
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by bms63** [comment]
These R-CMD checks use a certain R version which I think for (dplyr and rlang) might be a bit tricky.  I feel like something big happened with dplyr 1.0 and R version 4.0 that are not "entirely" backwards compatible with 3.6.  I'm not entirely sure why rlang 1.02 is falling over as the lock file has 1.02 in it.

**Comment by bms63** [comment]
@esimms999-gsk @thomas-neitmann @cicdguy I think I found the culprit for this failing action for 4.0.  This stage.dependecies is loading usethis which loads rlang 0.4.10 from what I can see in the Description fIle.  I think the order of this stuff might matter.

image

image

@thomas-neitmann we can ignore 3.6?

**Comment by bms63** [comment]
@thomas-neitmann I updated to snapshot.  Runs locally for 3.6, and passes 4.0 and latest release.

**Comment by cicdguy** [comment]
Dependency management is tricky with multiple R versions. Thanks for looking into this, and kudos @bms63!

**Comment by thomas-neitmann** [comment]
Thanks a lot for all your effort @esimms999-gsk and for finalizing @bms63!

**Review by thomas-neitmann — APPROVED** [review]

**Pull request merged**
