### PR TITLE
Documentation: Fixed Typo on derive_vars_dtm 

### LINKED ISSUE #1260: Documentation: typo on derive_vars_dtm page
### Please select a category the issue is focused on?

_No response_

### Let us know where something needs a refresh or put your idea here!

On the documentation [page ](https://pharmaverse.github.io/admiral/reference/derive_vars_dtm.html) for this function, there is a paragraph that says "..I.e., for new_vars_prefix = "AST" the variables ASTDT, ASTDTF, and ASTTMF are created." I think this is supposed to say "...**ASTDTM,** ASTDTF, and ASTTMF are created" ?

### LINKED ISSUE #1261: Documentation:  Typo on derive_vars_dtm
### Please select a category the issue is focused on?

_No response_

### Let us know where something needs a refresh or put your idea here!

On the [documentation page ](https://pharmaverse.github.io/admiral/reference/derive_vars_dtm.html) for this function, there is a an example given: impute_dtc(
"2020-11",
min_dates = list(
 ymd_hms("2020-12-06T12:12:12"),
 ymd_hms("2020-11-11T11:11:11")
),
date_imputation = "first"
)
I think "first" should be changed to "FIRST" as per the rest of the documentation on that page? The same example is also given on [this page](https://pharmaverse.github.io/admiral/reference/derive_vars_dt.html)

### PR DESCRIPTION
**Pull request by PrajwalBorkar**
Closes #1260 
Closes #1261

### CODE REVIEW

**Comment by thomas-neitmann** [comment]
@PrajwalBorkar Thanks for opening a PR. Instead of editing the `.Rd` file directly you would have to edit the header in the corresponding `.R` file and run `devtools::document()` to updated the `.Rd` file.

**Comment by PrajwalBorkar** [comment]
So I have to edit these changes in .R file. After that where I have to run the command can u explain the steps?

**Comment by thomas-neitmann** [comment]
You'll have to run the `devtools::document()` command in the R console. You might need to run `install.packages("devtools")` first.

**Comment by PrajwalBorkar** [comment]
Sorry, but i don't have any knowledge of R console and related stuff. So you may close the PR as I'm not able to solve issue.

**Comment by thomas-neitmann** [comment]
Alright, I see. Thanks a lot for your wiillingess to contribute anyway.

**Pull request closed without merging**
