### PR TITLE
Closes #1839 dummy function created 

### PR DESCRIPTION
**Pull request by kiwi5104679**
Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/CONTRIBUTING.html#detailed-development-process) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `main` branch until you have checked off each task.

- [x] Place Closes #1839 into the beginning of your Pull Request Title (Use Edit button in top-right if you need to update)
- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/). Run `styler::style_file()` to style R and Rmd files
- [x] Updated relevant unit tests or have written new unit tests, which should consider realistic data scenarios and edge cases, e.g. empty datasets, errors, boundary cases etc. - See [Unit Test Guide](https://pharmaverse.github.io/admiraldev/articles/unit_test_guidance.html#tests-should-be-robust-to-cover-realistic-data-scenarios)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#deprecation)?
- [x] Review the [Cheat Sheet](https://github.com/pharmaverse/admiral/blob/main/inst/cheatsheet/admiral_cheatsheet.pdf). Make any required updates to it by editing the file `inst/cheatsheet/admiral_cheatsheet.pptx` and re-upload a PDF and a PNG version of it to the same folder. (The PNG version can be created by taking a screenshot of the PDF version.)
- [x] Update to all relevant roxygen headers and examples, including keywords and families. Refer to the [categorization of functions](https://pharmaverse.github.io/admiraldev/articles/programming_strategy.html#categorization-of-functions) to tag appropriate keyword/family.
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md` under the header `# admiral (development version)` if the changes pertain to a user-facing function (i.e. it has an `@export` tag) or documentation aimed at users (rather than developers). A Developer Notes section is available in `NEWS.md` for tracking developer-facing issues.  
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue in the Development Section on the right hand side.
- [x] Address all merge conflicts and resolve appropriately
- [x] Pat yourself on the back for a job well done! Much love to your accomplishment!

### CODE REVIEW

**Comment by manciniedoardo** [comment]
Hi @kiwi5104679 - as discussed by email, you noted that your pkgbuild is failing:
image
I suggest setting `@leywords` and `@family` to an already existing category, e.g. `@ other_advanced`.

**Comment by kiwi5104679** [comment]
Hi @AndersAskeland , @manciniedoardo 

I could run pkgdown::build_site() and devtools::check()!!
The problem seemed to be caused by my environment of Rstudio.

image

I checked examples are displayed correctly and a new function occurs.
But the appearance of the page is a little different from [actual site](https://rstudio-dit.eu.novartis.net/s/2f10b367d8cb9ebd214f1/files/Desktop/pharmaverse/admiral/docs/dev/reference/).
 
image

Is this acceptable?

**Comment by manciniedoardo** [comment]
> Hi @AndersAskeland , @manciniedoardo
> 
> I could run pkgdown::build_site() and devtools::check()!! The problem seemed to be caused by my environment of Rstudio.
> 
> image
> 
> I checked examples are displayed correctly and a new function occurs. But the appearance of the page is a little different from [actual site](https://rstudio-dit.eu.novartis.net/s/2f10b367d8cb9ebd214f1/files/Desktop/pharmaverse/admiral/docs/dev/reference/).
> 
> image
> 
> Have you seen such a situation?

Probably fine for all intents and purposes in this exercise - well done!

**Comment by kiwi5104679** [comment]
@AndersAskeland , @manciniedoardo 
Thank you for checking. Got it.
Thanks to your supports, I managed to close this issue.
I may ask for support on a non-dummy issue, but thanks in advance!

**Pull request closed without merging**
