### PR TITLE
1129 styler

### LINKED ISSUE #1129: Fix styler findings
Fix styler findings to pass check.

### PR DESCRIPTION
**Pull request by bundfussr**
Closes #1129

Thank you for your Pull Request! We have developed this task checklist from the [Development Process Guide](https://pharmaverse.github.io/admiral/articles/development_process.html) to help with the final steps of the process. Completing the below tasks helps to ensure our reviewers can maximize their time on your code as well as making sure the admiral codebase remains robust and consistent.   

Please check off each taskbox as an acknowledgment that you completed the task or check off that it is not relevant to your Pull Request. This checklist is part of the Github Action workflows and the Pull Request will not be merged into the `devel` branch until you have checked off each task.

- [x] Code is formatted according to the [tidyverse style guide](https://style.tidyverse.org/) 
- [x] Updated relevant unit tests or have written new unit tests - See [Unit Test Guide](https://pharmaverse.github.io/admiral/articles/unit_test_guidance.html#writing-unit-tests-in-admiral-)
- [x] If you removed/replaced any function and/or function parameters, did you fully follow the [deprecation guidance](https://pharmaverse.github.io/admiral/articles/programming_strategy.html#deprecation-1)?
- [x] Update to all relevant roxygen headers and examples 
- [x] Run `devtools::document()` so all `.Rd` files in the `man` folder and the `NAMESPACE` file in the project root are updated appropriately
- [x] Address any updates needed for vignettes and/or templates
- [x] Update `NEWS.md`
- [x] Build admiral site `pkgdown::build_site()` and check that all affected examples are displayed correctly and that all new functions occur on the "[Reference](https://pharmaverse.github.io/admiral/reference/index.html)" page. 
- [x] Address or fix all lintr warnings and errors - `lintr::lint_package()`
- [x] Run `R CMD check` locally and address all errors and warnings - `devtools::check()`
- [x] Link the issue so that it closes after successful merging. 
- [x] Address all merge conflicts and resolve appropriately 
- [x] Pat yourself on the back for a job well done!  Much love to your accomplishment!

### CODE REVIEW

**Review by thomas-neitmann — APPROVED** [review]

**Comment by bundfussr** [comment]
@thomas-neitmann , thanks for approving the PR. Unfortunately, the styler check fails. When I run `style_file()` for the files listed as changed in the check, they are not changed. Do you have any idea why it behaves differently in the check and locally?

**Comment by thomas-neitmann** [comment]
The workflow seems to use {styler} v1.7.0 which is different from the one in our lock file. That might cause the discrepency. Let's try removing the line `renv::install("styler")` in the workflow such that it actually picks up the version specified in our renv.lock file.

**Comment by bundfussr** [comment]
Thanks @thomas-neitmann , your suggestion almost solved the issue. There are only two files left where the check finds a change but I do not see it locally.

Any more ideas?

**Comment by thomas-neitmann** [comment]
Looks like only the vignettes are causing issues now. Did you run styler on those locally?

**Comment by bundfussr** [comment]
@thomas-neitmann , I could fix all except occds vignette. If I style it locally, the file is not changed but the check reports a change.

I would propose that we ignore it for now and merge the PR. Then the correct styler version is available for other feature branches.

**Comment by thomas-neitmann** [comment]
Sounds good!

**Pull request merged**
